// generated by cargo xtask wasm; do not edit (source: crates/pemu-wasm/src/layout.rs)
//
// The raw wasm ABI, as the emulator Worker sees it. Every offset is a byte
// offset into wasm linear memory; every `SIZE` is the size of one record. Cursor cells
// are little-endian `u64` and are read through a `BigUint64Array` view.

/** Value `pemu_abi_version()` must return; a mismatch means the bundle and the core disagree. */
export const ABI_VERSION = 3;

/** Throws when the loaded core does not speak 3. */
export function assertAbiVersion(reported: number): void {
  if (reported !== ABI_VERSION) {
    throw new Error(
      `pemu wasm ABI ${reported} does not match this bundle's ${ABI_VERSION}; rebuild the core and run \`cargo xtask wasm\``,
    );
  }
}

/** `ResultHeader::status` of a successful call; anything else is an ErrorCode number and the payload is an ApiError JSON. */
export const STATUS_OK = 0;

/** Field offsets of the 12-byte result header every `res` call returns. */
export const ResultHeader = {
  PTR: 0,
  LEN: 4,
  STATUS: 8,
  SIZE: 12,
} as const;

/** `pemu_load` asset kinds. The web UI never sends RomElf: the ROM is compiled into the core. */
export const LoadKind = {
  RomElf: 0,
  MergedFlash: 1,
  AppElf: 2,
  BootloaderElf: 3,
  Efuse: 4,
} as const;
export type LoadKind = (typeof LoadKind)[keyof typeof LoadKind];

/** The `u32` `pemu_run` returns: a StopReason discriminant without its payload, which `pemu_last_stop` carries as JSON. */
export const StopCode = {
  Until: 0,
  MaxInsns: 1,
  Matcher: 2,
  Breakpoint: 3,
  Watchpoint: 4,
  GuestPanic: 5,
  Deadlock: 6,
  Stuck: 7,
  Tripwire: 8,
  Unmodeled: 9,
  Hle: 10,
  Halted: 11,
  ChipReset: 12,
  Sleep: 13,
} as const;
export type StopCode = (typeof StopCode)[keyof typeof StopCode];

/** Whether a stop is one of the two limits the pacing loop expects each slice. */
export function isLimitStop(code: number): boolean {
  return code === StopCode.Until || code === StopCode.MaxInsns;
}

/** Panel framebuffer, raw RGB565 (ST7789P3, 240x320). */
export const FRAME_WIDTH = 240;
export const FRAME_HEIGHT = 320;
/** `IoLayout.FRAME_DIRTY_FIRST` when no row changed since the last upload. */
export const DIRTY_NONE = 4294967295;
/** `IoLayout.FRAME_BACKLIGHT_SCALE` while the LEDC duty resolution is not modelled. */
export const DEFAULT_BACKLIGHT_SCALE = 1024;

/** Bits of `IoLayout.FRAME_FLAGS`. */
export const FrameFlag = {
  Powered: 1,
  Sleeping: 2,
  Inverted: 4,
  DisplayOn: 8,
  GlassComplement: 16,
} as const;
export type FrameFlag = (typeof FrameFlag)[keyof typeof FrameFlag];

/** Index into `IoLayout.RINGS`. `net` and `hci` are absent: they ship empty in wave 1. */
export const RingId = {
  UsjTx: 0,
  UsjRx: 1,
  Uart0Tx: 2,
  AudioOutSamples: 3,
  AudioOutRecords: 4,
  AudioInSamples: 5,
  AudioInRecords: 6,
  Events: 7,
  LinesUsjTx: 8,
  LinesUart0Tx: 9,
} as const;
export type RingId = (typeof RingId)[keyof typeof RingId];

export const RING_COUNT = 10;

/** Field offsets of one entry of `IoLayout.RINGS`. Slot `pos` of a ring lives at `BUF_PTR + (pos % CAPACITY) * ELEM_SIZE`. */
export const RingLayout = {
  BUF_PTR: 0,
  CAPACITY: 4,
  ELEM_SIZE: 8,
  CURSOR_SLOT: 12,
  SIZE: 16,
} as const;

/** Field offsets of what `pemu_io_layout(handle)` points at. */
export const IoLayout = {
  ABI_VERSION: 0,
  GENERATION: 4,
  CURSORS_PTR: 8,
  CURSOR_SLOTS: 12,
  FRAME_PTR: 16,
  FRAME_WIDTH: 20,
  FRAME_HEIGHT: 24,
  FRAME_FLAGS: 28,
  FRAME_BACKLIGHT: 32,
  FRAME_BACKLIGHT_SCALE: 36,
  FRAME_DIRTY_FIRST: 40,
  FRAME_DIRTY_LAST: 44,
  RINGS: 48,
  SIZE: 208,
} as const;

/** Cells of the cursor block that do not belong to a ring. A ring's head is cell `2 * RingId` and its tail the next cell. */
export const CursorSlot = {
  FrameGeneration: 20,
  AudioOutUnderflows: 21,
  AudioInUnderflows: 22,
  NowPs: 23,
} as const;
export type CursorSlot = (typeof CursorSlot)[keyof typeof CursorSlot];

export const CURSOR_SLOTS = 24;

/** Cell of the cursor block holding the ring's head. */
export function ringHeadSlot(ring: RingId): number {
  return ring * 2;
}

/** Cell of the cursor block holding the ring's tail. */
export function ringTailSlot(ring: RingId): number {
  return ring * 2 + 1;
}

/** Field offsets of one `audio_out` or `audio_in` record header. */
export const PcmRecord = {
  VT_START_PS: 0,
  FIRST: 8,
  FS: 16,
  CHANNELS: 20,
  SIZE: 24,
} as const;

/** Field offsets of one `events` record. */
export const HostEventRecord = {
  VT_PS: 0,
  ARG: 8,
  KIND: 16,
  SIZE: 24,
} as const;

/** Field offsets of one line-index record. */
export const LineMarkRecord = {
  OFFSET: 0,
  VT_PS: 8,
  STREAM: 16,
  SIZE: 24,
} as const;

/** `HostEventRecord.KIND` values. */
export const EventKind = {
  Reset: 0,
  Panic: 1,
  Sleep: 2,
  Power: 3,
  Frame: 4,
  UiSettled: 5,
  FidelityWarning: 6,
} as const;
export type EventKind = (typeof EventKind)[keyof typeof EventKind];

/** `LineMarkRecord.STREAM` values. */
export const SerialStream = {
  UsjTx: 0,
  Uart0Tx: 1,
} as const;
export type SerialStream = (typeof SerialStream)[keyof typeof SerialStream];

/** First word of a fixed-layout `pemu_input` batch (ASCII `PEIN`); a JSON batch starts with `[` or `{`. */
export const INPUT_BATCH_MAGIC = 1313424720;

/** Field offsets of a fixed-layout `pemu_input` batch header. */
export const InputBatchHeader = {
  MAGIC: 0,
  COUNT: 4,
  BLOB_OFF: 8,
  BLOB_LEN: 12,
  SIZE: 16,
} as const;

/** Field offsets of one fixed-layout input record. */
export const InputRecord = {
  AT_PS: 0,
  KIND: 8,
  A: 12,
  B: 16,
  C: 20,
  BLOB_OFF: 24,
  BLOB_LEN: 28,
  SIZE: 32,
} as const;

/** `InputRecord.AT_PS` meaning `At::Now`: the core stamps the input itself. */
export const AT_NOW = -1n;

/** `InputRecord.KIND` values, in the declaration order of `InputEvent`. */
export const InputKind = {
  Button: 0,
  Power: 1,
  UsbCable: 2,
  UsbClient: 3,
  UsbLine: 4,
  SerialIn: 5,
  Battery: 6,
  NfcTap: 7,
  MicChunk: 8,
  NetFrame: 9,
  HciPacket: 10,
  RtcEpoch: 11,
  Env: 12,
} as const;
export type InputKind = (typeof InputKind)[keyof typeof InputKind];

/** `InputRecord.A` values of `InputKind.Button` (Up, Down, Ok). */
export const ButtonId = {
  Up: 0,
  Down: 1,
  Ok: 2,
} as const;
export type ButtonId = (typeof ButtonId)[keyof typeof ButtonId];

