//! generated by cargo xtask codegen; do not edit.
//!
//! Interrupt sources of the ESP32-C3 interrupt matrix, generated from
//! `specs/irq-sources.toml`. Numbers are the ESP-IDF v5.5.3 `periph_interrupt_t` values of
//! `soc/esp32c3/include/soc/interrupts.h`, paired by name with the
//! `INTERRUPT_CORE0_*_MAP_REG` registers of `soc/esp32c3/register/soc/interrupt_core0_reg.h`
//! and checked against their offsets.

use serde::{Deserialize, Serialize};

/// One of the 62 interrupt sources: the IDF `periph_interrupt_t` number, generated by name,
/// never by position.
#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize)]
pub struct IrqSource(pub u8);

/// Number of interrupt sources, IDF `ETS_MAX_INTR_SOURCE`.
pub const SOURCE_COUNT: usize = 62;

/// One row of `specs/irq-sources.toml`.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct IrqSourceInfo {
    /// Constant name in [`irq`].
    pub name: &'static str,
    /// Source number.
    pub source: IrqSource,
    /// Offset of the source's MAP register from the INTERRUPT_CORE0 base (0x600C2000).
    pub map_off: u32,
}

/// Every source in number order: `SOURCES[n].source == IrqSource(n)`.
pub const SOURCES: [IrqSourceInfo; SOURCE_COUNT] = [
    IrqSourceInfo {
        name: "WIFI_MAC",
        source: irq::WIFI_MAC,
        map_off: 0x000,
    },
    IrqSourceInfo {
        name: "WIFI_MAC_NMI",
        source: irq::WIFI_MAC_NMI,
        map_off: 0x004,
    },
    IrqSourceInfo {
        name: "WIFI_PWR",
        source: irq::WIFI_PWR,
        map_off: 0x008,
    },
    IrqSourceInfo {
        name: "WIFI_BB",
        source: irq::WIFI_BB,
        map_off: 0x00C,
    },
    IrqSourceInfo {
        name: "BT_MAC",
        source: irq::BT_MAC,
        map_off: 0x010,
    },
    IrqSourceInfo {
        name: "BT_BB",
        source: irq::BT_BB,
        map_off: 0x014,
    },
    IrqSourceInfo {
        name: "BT_BB_NMI",
        source: irq::BT_BB_NMI,
        map_off: 0x018,
    },
    IrqSourceInfo {
        name: "RWBT",
        source: irq::RWBT,
        map_off: 0x01C,
    },
    IrqSourceInfo {
        name: "RWBLE",
        source: irq::RWBLE,
        map_off: 0x020,
    },
    IrqSourceInfo {
        name: "RWBT_NMI",
        source: irq::RWBT_NMI,
        map_off: 0x024,
    },
    IrqSourceInfo {
        name: "RWBLE_NMI",
        source: irq::RWBLE_NMI,
        map_off: 0x028,
    },
    IrqSourceInfo {
        name: "I2C_MASTER",
        source: irq::I2C_MASTER,
        map_off: 0x02C,
    },
    IrqSourceInfo {
        name: "SLC0",
        source: irq::SLC0,
        map_off: 0x030,
    },
    IrqSourceInfo {
        name: "SLC1",
        source: irq::SLC1,
        map_off: 0x034,
    },
    IrqSourceInfo {
        name: "APB_CTRL",
        source: irq::APB_CTRL,
        map_off: 0x038,
    },
    IrqSourceInfo {
        name: "UHCI0",
        source: irq::UHCI0,
        map_off: 0x03C,
    },
    IrqSourceInfo {
        name: "GPIO",
        source: irq::GPIO,
        map_off: 0x040,
    },
    IrqSourceInfo {
        name: "GPIO_NMI",
        source: irq::GPIO_NMI,
        map_off: 0x044,
    },
    IrqSourceInfo {
        name: "SPI1",
        source: irq::SPI1,
        map_off: 0x048,
    },
    IrqSourceInfo {
        name: "SPI2",
        source: irq::SPI2,
        map_off: 0x04C,
    },
    IrqSourceInfo {
        name: "I2S0",
        source: irq::I2S0,
        map_off: 0x050,
    },
    IrqSourceInfo {
        name: "UART0",
        source: irq::UART0,
        map_off: 0x054,
    },
    IrqSourceInfo {
        name: "UART1",
        source: irq::UART1,
        map_off: 0x058,
    },
    IrqSourceInfo {
        name: "LEDC",
        source: irq::LEDC,
        map_off: 0x05C,
    },
    IrqSourceInfo {
        name: "EFUSE",
        source: irq::EFUSE,
        map_off: 0x060,
    },
    IrqSourceInfo {
        name: "TWAI",
        source: irq::TWAI,
        map_off: 0x064,
    },
    IrqSourceInfo {
        name: "USB_SERIAL_JTAG",
        source: irq::USB_SERIAL_JTAG,
        map_off: 0x068,
    },
    IrqSourceInfo {
        name: "RTC_CORE",
        source: irq::RTC_CORE,
        map_off: 0x06C,
    },
    IrqSourceInfo {
        name: "RMT",
        source: irq::RMT,
        map_off: 0x070,
    },
    IrqSourceInfo {
        name: "I2C_EXT0",
        source: irq::I2C_EXT0,
        map_off: 0x074,
    },
    IrqSourceInfo {
        name: "TIMER1",
        source: irq::TIMER1,
        map_off: 0x078,
    },
    IrqSourceInfo {
        name: "TIMER2",
        source: irq::TIMER2,
        map_off: 0x07C,
    },
    IrqSourceInfo {
        name: "TG0_T0",
        source: irq::TG0_T0,
        map_off: 0x080,
    },
    IrqSourceInfo {
        name: "TG0_WDT",
        source: irq::TG0_WDT,
        map_off: 0x084,
    },
    IrqSourceInfo {
        name: "TG1_T0",
        source: irq::TG1_T0,
        map_off: 0x088,
    },
    IrqSourceInfo {
        name: "TG1_WDT",
        source: irq::TG1_WDT,
        map_off: 0x08C,
    },
    IrqSourceInfo {
        name: "CACHE_IA",
        source: irq::CACHE_IA,
        map_off: 0x090,
    },
    IrqSourceInfo {
        name: "SYSTIMER_TARGET0",
        source: irq::SYSTIMER_TARGET0,
        map_off: 0x094,
    },
    IrqSourceInfo {
        name: "SYSTIMER_TARGET1",
        source: irq::SYSTIMER_TARGET1,
        map_off: 0x098,
    },
    IrqSourceInfo {
        name: "SYSTIMER_TARGET2",
        source: irq::SYSTIMER_TARGET2,
        map_off: 0x09C,
    },
    IrqSourceInfo {
        name: "SPI_MEM_REJECT",
        source: irq::SPI_MEM_REJECT,
        map_off: 0x0A0,
    },
    IrqSourceInfo {
        name: "ICACHE_PRELOAD0",
        source: irq::ICACHE_PRELOAD0,
        map_off: 0x0A4,
    },
    IrqSourceInfo {
        name: "ICACHE_SYNC0",
        source: irq::ICACHE_SYNC0,
        map_off: 0x0A8,
    },
    IrqSourceInfo {
        name: "APB_ADC",
        source: irq::APB_ADC,
        map_off: 0x0AC,
    },
    IrqSourceInfo {
        name: "DMA_CH0",
        source: irq::DMA_CH0,
        map_off: 0x0B0,
    },
    IrqSourceInfo {
        name: "DMA_CH1",
        source: irq::DMA_CH1,
        map_off: 0x0B4,
    },
    IrqSourceInfo {
        name: "DMA_CH2",
        source: irq::DMA_CH2,
        map_off: 0x0B8,
    },
    IrqSourceInfo {
        name: "RSA",
        source: irq::RSA,
        map_off: 0x0BC,
    },
    IrqSourceInfo {
        name: "AES",
        source: irq::AES,
        map_off: 0x0C0,
    },
    IrqSourceInfo {
        name: "SHA",
        source: irq::SHA,
        map_off: 0x0C4,
    },
    IrqSourceInfo {
        name: "FROM_CPU_INTR0",
        source: irq::FROM_CPU_INTR0,
        map_off: 0x0C8,
    },
    IrqSourceInfo {
        name: "FROM_CPU_INTR1",
        source: irq::FROM_CPU_INTR1,
        map_off: 0x0CC,
    },
    IrqSourceInfo {
        name: "FROM_CPU_INTR2",
        source: irq::FROM_CPU_INTR2,
        map_off: 0x0D0,
    },
    IrqSourceInfo {
        name: "FROM_CPU_INTR3",
        source: irq::FROM_CPU_INTR3,
        map_off: 0x0D4,
    },
    IrqSourceInfo {
        name: "ASSIST_DEBUG",
        source: irq::ASSIST_DEBUG,
        map_off: 0x0D8,
    },
    IrqSourceInfo {
        name: "DMA_APBPERI_PMS",
        source: irq::DMA_APBPERI_PMS,
        map_off: 0x0DC,
    },
    IrqSourceInfo {
        name: "CORE0_IRAM0_PMS",
        source: irq::CORE0_IRAM0_PMS,
        map_off: 0x0E0,
    },
    IrqSourceInfo {
        name: "CORE0_DRAM0_PMS",
        source: irq::CORE0_DRAM0_PMS,
        map_off: 0x0E4,
    },
    IrqSourceInfo {
        name: "CORE0_PIF_PMS",
        source: irq::CORE0_PIF_PMS,
        map_off: 0x0E8,
    },
    IrqSourceInfo {
        name: "CORE0_PIF_PMS_SIZE",
        source: irq::CORE0_PIF_PMS_SIZE,
        map_off: 0x0EC,
    },
    IrqSourceInfo {
        name: "BAK_PMS_VIOLATE",
        source: irq::BAK_PMS_VIOLATE,
        map_off: 0x0F0,
    },
    IrqSourceInfo {
        name: "CACHE_CORE0_ACS",
        source: irq::CACHE_CORE0_ACS,
        map_off: 0x0F4,
    },
];

/// Named interrupt sources.
pub mod irq {
    use super::IrqSource;

    /// `ETS_WIFI_MAC_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_MAC_INTR_MAP_REG` (0x000).
    pub const WIFI_MAC: IrqSource = IrqSource(0);

    /// `ETS_WIFI_MAC_NMI_SOURCE`, MAP register `INTERRUPT_CORE0_MAC_NMI_MAP_REG` (0x004).
    pub const WIFI_MAC_NMI: IrqSource = IrqSource(1);

    /// `ETS_WIFI_PWR_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_PWR_INTR_MAP_REG` (0x008).
    pub const WIFI_PWR: IrqSource = IrqSource(2);

    /// `ETS_WIFI_BB_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_BB_INT_MAP_REG` (0x00C).
    pub const WIFI_BB: IrqSource = IrqSource(3);

    /// `ETS_BT_MAC_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_BT_MAC_INT_MAP_REG` (0x010).
    pub const BT_MAC: IrqSource = IrqSource(4);

    /// `ETS_BT_BB_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_BT_BB_INT_MAP_REG` (0x014).
    pub const BT_BB: IrqSource = IrqSource(5);

    /// `ETS_BT_BB_NMI_SOURCE`, MAP register `INTERRUPT_CORE0_BT_BB_NMI_MAP_REG` (0x018).
    pub const BT_BB_NMI: IrqSource = IrqSource(6);

    /// `ETS_RWBT_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_RWBT_IRQ_MAP_REG` (0x01C).
    pub const RWBT: IrqSource = IrqSource(7);

    /// `ETS_RWBLE_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_RWBLE_IRQ_MAP_REG` (0x020).
    pub const RWBLE: IrqSource = IrqSource(8);

    /// `ETS_RWBT_NMI_SOURCE`, MAP register `INTERRUPT_CORE0_RWBT_NMI_MAP_REG` (0x024).
    pub const RWBT_NMI: IrqSource = IrqSource(9);

    /// `ETS_RWBLE_NMI_SOURCE`, MAP register `INTERRUPT_CORE0_RWBLE_NMI_MAP_REG` (0x028).
    pub const RWBLE_NMI: IrqSource = IrqSource(10);

    /// `ETS_I2C_MASTER_SOURCE`, MAP register `INTERRUPT_CORE0_I2C_MST_INT_MAP_REG` (0x02C).
    pub const I2C_MASTER: IrqSource = IrqSource(11);

    /// `ETS_SLC0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SLC0_INTR_MAP_REG` (0x030).
    pub const SLC0: IrqSource = IrqSource(12);

    /// `ETS_SLC1_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SLC1_INTR_MAP_REG` (0x034).
    pub const SLC1: IrqSource = IrqSource(13);

    /// `ETS_APB_CTRL_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_APB_CTRL_INTR_MAP_REG` (0x038).
    pub const APB_CTRL: IrqSource = IrqSource(14);

    /// `ETS_UHCI0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_UHCI0_INTR_MAP_REG` (0x03C).
    pub const UHCI0: IrqSource = IrqSource(15);

    /// `ETS_GPIO_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_MAP_REG` (0x040).
    pub const GPIO: IrqSource = IrqSource(16);

    /// `ETS_GPIO_NMI_SOURCE`, MAP register `INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_NMI_MAP_REG` (0x044).
    pub const GPIO_NMI: IrqSource = IrqSource(17);

    /// `ETS_SPI1_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SPI_INTR_1_MAP_REG` (0x048).
    pub const SPI1: IrqSource = IrqSource(18);

    /// `ETS_SPI2_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SPI_INTR_2_MAP_REG` (0x04C).
    pub const SPI2: IrqSource = IrqSource(19);

    /// `ETS_I2S0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_I2S_INT_MAP_REG` (0x050).
    pub const I2S0: IrqSource = IrqSource(20);

    /// `ETS_UART0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_UART_INTR_MAP_REG` (0x054).
    pub const UART0: IrqSource = IrqSource(21);

    /// `ETS_UART1_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_UART1_INTR_MAP_REG` (0x058).
    pub const UART1: IrqSource = IrqSource(22);

    /// `ETS_LEDC_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_LEDC_INT_MAP_REG` (0x05C).
    pub const LEDC: IrqSource = IrqSource(23);

    /// `ETS_EFUSE_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_EFUSE_INT_MAP_REG` (0x060).
    pub const EFUSE: IrqSource = IrqSource(24);

    /// `ETS_TWAI_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_CAN_INT_MAP_REG` (0x064).
    pub const TWAI: IrqSource = IrqSource(25);

    /// `ETS_USB_SERIAL_JTAG_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_USB_INTR_MAP_REG` (0x068).
    pub const USB_SERIAL_JTAG: IrqSource = IrqSource(26);

    /// `ETS_RTC_CORE_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_RTC_CORE_INTR_MAP_REG` (0x06C).
    pub const RTC_CORE: IrqSource = IrqSource(27);

    /// `ETS_RMT_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_RMT_INTR_MAP_REG` (0x070).
    pub const RMT: IrqSource = IrqSource(28);

    /// `ETS_I2C_EXT0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_I2C_EXT0_INTR_MAP_REG` (0x074).
    pub const I2C_EXT0: IrqSource = IrqSource(29);

    /// `ETS_TIMER1_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_TIMER_INT1_MAP_REG` (0x078).
    pub const TIMER1: IrqSource = IrqSource(30);

    /// `ETS_TIMER2_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_TIMER_INT2_MAP_REG` (0x07C).
    pub const TIMER2: IrqSource = IrqSource(31);

    /// `ETS_TG0_T0_LEVEL_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_TG_T0_INT_MAP_REG` (0x080).
    pub const TG0_T0: IrqSource = IrqSource(32);

    /// `ETS_TG0_WDT_LEVEL_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_TG_WDT_INT_MAP_REG` (0x084).
    pub const TG0_WDT: IrqSource = IrqSource(33);

    /// `ETS_TG1_T0_LEVEL_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_TG1_T0_INT_MAP_REG` (0x088).
    pub const TG1_T0: IrqSource = IrqSource(34);

    /// `ETS_TG1_WDT_LEVEL_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_TG1_WDT_INT_MAP_REG` (0x08C).
    pub const TG1_WDT: IrqSource = IrqSource(35);

    /// `ETS_CACHE_IA_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_CACHE_IA_INT_MAP_REG` (0x090).
    pub const CACHE_IA: IrqSource = IrqSource(36);

    /// `ETS_SYSTIMER_TARGET0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SYSTIMER_TARGET0_INT_MAP_REG` (0x094).
    pub const SYSTIMER_TARGET0: IrqSource = IrqSource(37);

    /// `ETS_SYSTIMER_TARGET1_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SYSTIMER_TARGET1_INT_MAP_REG` (0x098).
    pub const SYSTIMER_TARGET1: IrqSource = IrqSource(38);

    /// `ETS_SYSTIMER_TARGET2_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SYSTIMER_TARGET2_INT_MAP_REG` (0x09C).
    pub const SYSTIMER_TARGET2: IrqSource = IrqSource(39);

    /// `ETS_SPI_MEM_REJECT_CACHE_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SPI_MEM_REJECT_INTR_MAP_REG` (0x0A0).
    pub const SPI_MEM_REJECT: IrqSource = IrqSource(40);

    /// `ETS_ICACHE_PRELOAD0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_ICACHE_PRELOAD_INT_MAP_REG` (0x0A4).
    pub const ICACHE_PRELOAD0: IrqSource = IrqSource(41);

    /// `ETS_ICACHE_SYNC0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_ICACHE_SYNC_INT_MAP_REG` (0x0A8).
    pub const ICACHE_SYNC0: IrqSource = IrqSource(42);

    /// `ETS_APB_ADC_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_APB_ADC_INT_MAP_REG` (0x0AC).
    pub const APB_ADC: IrqSource = IrqSource(43);

    /// `ETS_DMA_CH0_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_DMA_CH0_INT_MAP_REG` (0x0B0).
    pub const DMA_CH0: IrqSource = IrqSource(44);

    /// `ETS_DMA_CH1_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_DMA_CH1_INT_MAP_REG` (0x0B4).
    pub const DMA_CH1: IrqSource = IrqSource(45);

    /// `ETS_DMA_CH2_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_DMA_CH2_INT_MAP_REG` (0x0B8).
    pub const DMA_CH2: IrqSource = IrqSource(46);

    /// `ETS_RSA_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_RSA_INT_MAP_REG` (0x0BC).
    pub const RSA: IrqSource = IrqSource(47);

    /// `ETS_AES_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_AES_INT_MAP_REG` (0x0C0).
    pub const AES: IrqSource = IrqSource(48);

    /// `ETS_SHA_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_SHA_INT_MAP_REG` (0x0C4).
    pub const SHA: IrqSource = IrqSource(49);

    /// `ETS_FROM_CPU_INTR0_SOURCE`, MAP register `INTERRUPT_CORE0_CPU_INTR_FROM_CPU_0_MAP_REG` (0x0C8).
    pub const FROM_CPU_INTR0: IrqSource = IrqSource(50);

    /// `ETS_FROM_CPU_INTR1_SOURCE`, MAP register `INTERRUPT_CORE0_CPU_INTR_FROM_CPU_1_MAP_REG` (0x0CC).
    pub const FROM_CPU_INTR1: IrqSource = IrqSource(51);

    /// `ETS_FROM_CPU_INTR2_SOURCE`, MAP register `INTERRUPT_CORE0_CPU_INTR_FROM_CPU_2_MAP_REG` (0x0D0).
    pub const FROM_CPU_INTR2: IrqSource = IrqSource(52);

    /// `ETS_FROM_CPU_INTR3_SOURCE`, MAP register `INTERRUPT_CORE0_CPU_INTR_FROM_CPU_3_MAP_REG` (0x0D4).
    pub const FROM_CPU_INTR3: IrqSource = IrqSource(53);

    /// `ETS_ASSIST_DEBUG_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_ASSIST_DEBUG_INTR_MAP_REG` (0x0D8).
    pub const ASSIST_DEBUG: IrqSource = IrqSource(54);

    /// `ETS_DMA_APBPERI_PMS_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP_REG` (0x0DC).
    pub const DMA_APBPERI_PMS: IrqSource = IrqSource(55);

    /// `ETS_CORE0_IRAM0_PMS_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_REG` (0x0E0).
    pub const CORE0_IRAM0_PMS: IrqSource = IrqSource(56);

    /// `ETS_CORE0_DRAM0_PMS_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_REG` (0x0E4).
    pub const CORE0_DRAM0_PMS: IrqSource = IrqSource(57);

    /// `ETS_CORE0_PIF_PMS_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_REG` (0x0E8).
    pub const CORE0_PIF_PMS: IrqSource = IrqSource(58);

    /// `ETS_CORE0_PIF_PMS_SIZE_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_REG` (0x0EC).
    pub const CORE0_PIF_PMS_SIZE: IrqSource = IrqSource(59);

    /// `ETS_BAK_PMS_VIOLATE_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_BACKUP_PMS_VIOLATE_INTR_MAP_REG` (0x0F0).
    pub const BAK_PMS_VIOLATE: IrqSource = IrqSource(60);

    /// `ETS_CACHE_CORE0_ACS_INTR_SOURCE`, MAP register `INTERRUPT_CORE0_CACHE_CORE0_ACS_INT_MAP_REG` (0x0F4).
    pub const CACHE_CORE0_ACS: IrqSource = IrqSource(61);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Numbering by name agrees with the MAP register offsets.
    #[test]
    fn irq_numbering_matches_map_offsets() {
        assert_eq!(irq::SYSTIMER_TARGET2, IrqSource(39));
        assert_eq!(SOURCES[39].map_off, 0x09C);
        assert_eq!(irq::SPI_MEM_REJECT, IrqSource(40));
        assert_eq!(SOURCES[40].map_off, 0x0A0);
        assert_eq!(irq::FROM_CPU_INTR0, IrqSource(50));
        assert_eq!(SOURCES[50].map_off, 0x0C8);
        assert_eq!(irq::CACHE_CORE0_ACS, IrqSource(61));
        assert_eq!(SOURCES[61].map_off, 0x0F4);
        for (n, s) in SOURCES.iter().enumerate() {
            assert_eq!(usize::from(s.source.0), n, "{}", s.name);
            assert!(s.map_off.is_multiple_of(4), "{}", s.name);
            assert_eq!(s.map_off / 4, u32::from(s.source.0), "{}", s.name);
        }
    }
}
