//! The TypeScript form of [`crate::layout`]: `xtask wasm` writes [`layout_ts`] to
//! `web/src/worker/layout.ts`, or compares with `--check`. It lives here so the Rust constants
//! are the only source of truth; `tests/layout_ts.rs` fails when the committed file drifted.

use core::fmt::Write as _;

use pemu_core::hostio::SerialStream;

use crate::layout::{
    ABI_VERSION, AT_NOW, BUTTON_IDS, CURSOR_SLOTS, DEFAULT_BACKLIGHT_SCALE, DIRTY_NONE,
    EVENT_KINDS, FRAME_FLAG_DISPLAY_ON, FRAME_FLAG_GLASS_COMPLEMENT, FRAME_FLAG_INVERTED,
    FRAME_FLAG_POWERED, FRAME_FLAG_SLEEPING, FRAME_HEIGHT, FRAME_WIDTH, INPUT_BATCH_MAGIC,
    InputKind, LoadKind, RING_COUNT, RingId, SLOT_AUDIO_IN_UNDERFLOWS, SLOT_AUDIO_OUT_UNDERFLOWS,
    SLOT_FRAME_GENERATION, SLOT_NOW_PS, STATUS_OK, StopCode, event_kind_code, event_kind_name,
    serial_stream_code, serial_stream_name,
};

/// First line of the generated file; `xtask wasm --check` and the web build both rely on it.
pub const GENERATED_HEADER: &str =
    "// generated by cargo xtask wasm; do not edit (source: crates/pemu-wasm/src/layout.rs)";

/// The whole of `web/src/worker/layout.ts`, ending in a newline.
pub fn layout_ts() -> String {
    let mut out = String::with_capacity(8192);
    preamble(&mut out);
    versions(&mut out);
    result_header(&mut out);
    frame(&mut out);
    rings(&mut out);
    records(&mut out);
    inputs(&mut out);
    out
}

fn preamble(out: &mut String) {
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str(
        "//\n\
         // The raw wasm ABI, as the emulator Worker sees it. Every offset is a byte\n\
         // offset into wasm linear memory; every `SIZE` is the size of one record. Cursor cells\n\
         // are little-endian `u64` and are read through a `BigUint64Array` view.\n\n",
    );
}

fn emit_object(out: &mut String, name: &str, doc: &str, members: &[(String, String)]) {
    let _ = writeln!(out, "/** {doc} */");
    let _ = writeln!(out, "export const {name} = {{");
    for (member, value) in members {
        let _ = writeln!(out, "  {member}: {value},");
    }
    let _ = writeln!(out, "}} as const;");
}

/// An object plus the union type of its values, a strict-mode-friendly TypeScript `enum`.
fn emit_enum(out: &mut String, name: &str, doc: &str, members: &[(String, String)]) {
    emit_object(out, name, doc, members);
    let _ = writeln!(
        out,
        "export type {name} = (typeof {name})[keyof typeof {name}];\n"
    );
}

/// A table of byte offsets, with no union type: `RingLayout` names a record shape, not a value.
fn emit_offsets(out: &mut String, name: &str, doc: &str, members: &[(&str, usize)]) {
    let members: Vec<(String, String)> = members
        .iter()
        .map(|(member, offset)| ((*member).to_string(), offset.to_string()))
        .collect();
    emit_object(out, name, doc, &members);
    out.push('\n');
}

fn pairs<T: Copy, F: Fn(T) -> (&'static str, String)>(items: &[T], f: F) -> Vec<(String, String)> {
    items
        .iter()
        .map(|item| {
            let (name, value) = f(*item);
            (name.to_string(), value)
        })
        .collect()
}

fn versions(out: &mut String) {
    let _ = writeln!(
        out,
        "/** Value `pemu_abi_version()` must return; a mismatch means the bundle and the core \
         disagree. */"
    );
    let _ = writeln!(out, "export const ABI_VERSION = {ABI_VERSION};\n");
    let _ = writeln!(
        out,
        "/** Throws when the loaded core does not speak {ABI_VERSION}. */"
    );
    out.push_str(
        "export function assertAbiVersion(reported: number): void {\n\
         \x20 if (reported !== ABI_VERSION) {\n\
         \x20   throw new Error(\n\
         \x20     `pemu wasm ABI ${reported} does not match this bundle's ${ABI_VERSION}; \
         rebuild the core and run \\`cargo xtask wasm\\``,\n\
         \x20   );\n\
         \x20 }\n\
         }\n\n",
    );
}

fn result_header(out: &mut String) {
    let _ = writeln!(
        out,
        "/** `ResultHeader::status` of a successful call; anything else is an ErrorCode number \
         and the payload is an ApiError JSON. */"
    );
    let _ = writeln!(out, "export const STATUS_OK = {STATUS_OK};\n");
    emit_offsets(
        out,
        "ResultHeader",
        "Field offsets of the 12-byte result header every `res` call returns.",
        &[("PTR", 0), ("LEN", 4), ("STATUS", 8), ("SIZE", 12)],
    );
    emit_enum(
        out,
        "LoadKind",
        "`pemu_load` asset kinds. The web UI never sends RomElf: the ROM is compiled into the \
         core.",
        &pairs(&LoadKind::ALL, |kind| {
            (kind.name(), (kind as u32).to_string())
        }),
    );
    emit_enum(
        out,
        "StopCode",
        "The `u32` `pemu_run` returns: a StopReason discriminant without its payload, which \
         `pemu_last_stop` carries as JSON.",
        &pairs(&StopCode::ALL, |code| {
            (code.name(), (code as u32).to_string())
        }),
    );
    out.push_str(
        "/** Whether a stop is one of the two limits the pacing loop expects each slice. */\n\
         export function isLimitStop(code: number): boolean {\n\
         \x20 return code === StopCode.Until || code === StopCode.MaxInsns;\n\
         }\n\n",
    );
}

fn frame(out: &mut String) {
    let _ = writeln!(
        out,
        "/** Panel framebuffer, raw RGB565 (ST7789P3, 240x320). */"
    );
    let _ = writeln!(out, "export const FRAME_WIDTH = {FRAME_WIDTH};");
    let _ = writeln!(out, "export const FRAME_HEIGHT = {FRAME_HEIGHT};");
    let _ = writeln!(
        out,
        "/** `IoLayout.FRAME_DIRTY_FIRST` when no row changed since the last upload. */"
    );
    let _ = writeln!(out, "export const DIRTY_NONE = {DIRTY_NONE};");
    let _ = writeln!(
        out,
        "/** `IoLayout.FRAME_BACKLIGHT_SCALE` while the LEDC duty resolution is not modelled. */"
    );
    let _ = writeln!(
        out,
        "export const DEFAULT_BACKLIGHT_SCALE = {DEFAULT_BACKLIGHT_SCALE};\n"
    );
    emit_enum(
        out,
        "FrameFlag",
        "Bits of `IoLayout.FRAME_FLAGS`.",
        &[
            ("Powered".to_string(), FRAME_FLAG_POWERED.to_string()),
            ("Sleeping".to_string(), FRAME_FLAG_SLEEPING.to_string()),
            ("Inverted".to_string(), FRAME_FLAG_INVERTED.to_string()),
            ("DisplayOn".to_string(), FRAME_FLAG_DISPLAY_ON.to_string()),
            (
                "GlassComplement".to_string(),
                FRAME_FLAG_GLASS_COMPLEMENT.to_string(),
            ),
        ],
    );
}

fn rings(out: &mut String) {
    emit_enum(
        out,
        "RingId",
        "Index into `IoLayout.RINGS`. `net` and `hci` are absent: they ship empty in wave 1.",
        &pairs(&RingId::ALL, |ring| {
            (ring.name(), (ring as u32).to_string())
        }),
    );
    let _ = writeln!(out, "export const RING_COUNT = {RING_COUNT};\n");
    emit_offsets(
        out,
        "RingLayout",
        "Field offsets of one entry of `IoLayout.RINGS`. Slot `pos` of a ring lives at \
         `BUF_PTR + (pos % CAPACITY) * ELEM_SIZE`.",
        &[
            ("BUF_PTR", 0),
            ("CAPACITY", 4),
            ("ELEM_SIZE", 8),
            ("CURSOR_SLOT", 12),
            ("SIZE", 16),
        ],
    );
    emit_offsets(
        out,
        "IoLayout",
        "Field offsets of what `pemu_io_layout(handle)` points at.",
        &[
            ("ABI_VERSION", 0),
            ("GENERATION", 4),
            ("CURSORS_PTR", 8),
            ("CURSOR_SLOTS", 12),
            ("FRAME_PTR", 16),
            ("FRAME_WIDTH", 20),
            ("FRAME_HEIGHT", 24),
            ("FRAME_FLAGS", 28),
            ("FRAME_BACKLIGHT", 32),
            ("FRAME_BACKLIGHT_SCALE", 36),
            ("FRAME_DIRTY_FIRST", 40),
            ("FRAME_DIRTY_LAST", 44),
            ("RINGS", 48),
            ("SIZE", 48 + 16 * RING_COUNT),
        ],
    );
    emit_enum(
        out,
        "CursorSlot",
        "Cells of the cursor block that do not belong to a ring. A ring's head is cell \
         `2 * RingId` and its tail the next cell.",
        &[
            (
                "FrameGeneration".to_string(),
                SLOT_FRAME_GENERATION.to_string(),
            ),
            (
                "AudioOutUnderflows".to_string(),
                SLOT_AUDIO_OUT_UNDERFLOWS.to_string(),
            ),
            (
                "AudioInUnderflows".to_string(),
                SLOT_AUDIO_IN_UNDERFLOWS.to_string(),
            ),
            ("NowPs".to_string(), SLOT_NOW_PS.to_string()),
        ],
    );
    let _ = writeln!(out, "export const CURSOR_SLOTS = {CURSOR_SLOTS};\n");
    out.push_str(
        "/** Cell of the cursor block holding the ring's head. */\n\
         export function ringHeadSlot(ring: RingId): number {\n\
         \x20 return ring * 2;\n\
         }\n\n\
         /** Cell of the cursor block holding the ring's tail. */\n\
         export function ringTailSlot(ring: RingId): number {\n\
         \x20 return ring * 2 + 1;\n\
         }\n\n",
    );
}

fn records(out: &mut String) {
    emit_offsets(
        out,
        "PcmRecord",
        "Field offsets of one `audio_out` or `audio_in` record header.",
        &[
            ("VT_START_PS", 0),
            ("FIRST", 8),
            ("FS", 16),
            ("CHANNELS", 20),
            ("SIZE", 24),
        ],
    );
    emit_offsets(
        out,
        "HostEventRecord",
        "Field offsets of one `events` record.",
        &[("VT_PS", 0), ("ARG", 8), ("KIND", 16), ("SIZE", 24)],
    );
    emit_offsets(
        out,
        "LineMarkRecord",
        "Field offsets of one line-index record.",
        &[("OFFSET", 0), ("VT_PS", 8), ("STREAM", 16), ("SIZE", 24)],
    );
    emit_enum(
        out,
        "EventKind",
        "`HostEventRecord.KIND` values.",
        &EVENT_KINDS
            .iter()
            .map(|kind| {
                (
                    event_kind_name(*kind).to_string(),
                    event_kind_code(*kind).to_string(),
                )
            })
            .collect::<Vec<_>>(),
    );
    emit_enum(
        out,
        "SerialStream",
        "`LineMarkRecord.STREAM` values.",
        &SerialStream::ALL
            .iter()
            .map(|stream| {
                (
                    serial_stream_name(*stream).to_string(),
                    serial_stream_code(*stream).to_string(),
                )
            })
            .collect::<Vec<_>>(),
    );
}

fn inputs(out: &mut String) {
    let _ = writeln!(
        out,
        "/** First word of a fixed-layout `pemu_input` batch (ASCII `PEIN`); a JSON batch starts \
         with `[` or `{{`. */"
    );
    let _ = writeln!(
        out,
        "export const INPUT_BATCH_MAGIC = {INPUT_BATCH_MAGIC};\n"
    );
    emit_offsets(
        out,
        "InputBatchHeader",
        "Field offsets of a fixed-layout `pemu_input` batch header.",
        &[
            ("MAGIC", 0),
            ("COUNT", 4),
            ("BLOB_OFF", 8),
            ("BLOB_LEN", 12),
            ("SIZE", 16),
        ],
    );
    emit_offsets(
        out,
        "InputRecord",
        "Field offsets of one fixed-layout input record.",
        &[
            ("AT_PS", 0),
            ("KIND", 8),
            ("A", 12),
            ("B", 16),
            ("C", 20),
            ("BLOB_OFF", 24),
            ("BLOB_LEN", 28),
            ("SIZE", 32),
        ],
    );
    let _ = writeln!(
        out,
        "/** `InputRecord.AT_PS` meaning `At::Now`: the core stamps the input itself. */"
    );
    let _ = writeln!(out, "export const AT_NOW = {AT_NOW}n;\n");
    emit_enum(
        out,
        "InputKind",
        "`InputRecord.KIND` values, in the declaration order of `InputEvent`.",
        &pairs(&InputKind::ALL, |kind| {
            (kind.name(), (kind as u32).to_string())
        }),
    );
    emit_enum(
        out,
        "ButtonId",
        "`InputRecord.A` values of `InputKind.Button` (Up, Down, Ok).",
        &BUTTON_IDS
            .iter()
            .map(|(name, code)| ((*name).to_string(), code.to_string()))
            .collect::<Vec<_>>(),
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_generated_module_starts_with_the_header_and_ends_with_a_newline() {
        let ts = layout_ts();
        assert!(ts.starts_with(GENERATED_HEADER));
        assert!(ts.ends_with('\n'));
        assert!(!ts.ends_with("\n\n\n"));
    }

    #[test]
    fn every_constant_reaches_the_module() {
        let ts = layout_ts();
        assert!(ts.contains(&format!("export const ABI_VERSION = {ABI_VERSION};")));
        assert!(ts.contains(&format!("export const FRAME_WIDTH = {FRAME_WIDTH};")));
        assert!(ts.contains(&format!("export const FRAME_HEIGHT = {FRAME_HEIGHT};")));
        assert!(ts.contains(&format!("export const CURSOR_SLOTS = {CURSOR_SLOTS};")));
        assert!(ts.contains(&format!(
            "export const INPUT_BATCH_MAGIC = {INPUT_BATCH_MAGIC};"
        )));
        assert!(ts.contains(&format!("export const AT_NOW = {AT_NOW}n;")));
        for ring in RingId::ALL {
            assert!(ts.contains(&format!("  {}: {},", ring.name(), ring as u32)));
        }
        for code in StopCode::ALL {
            assert!(ts.contains(&format!("  {}: {},", code.name(), code as u32)));
        }
        for kind in InputKind::ALL {
            assert!(ts.contains(&format!("  {}: {},", kind.name(), kind as u32)));
        }
        for kind in LoadKind::ALL {
            assert!(ts.contains(&format!("  {}: {},", kind.name(), kind as u32)));
        }
    }

    #[test]
    fn the_io_layout_size_follows_the_ring_count() {
        let ts = layout_ts();
        let size = core::mem::size_of::<crate::layout::IoLayout>();
        assert!(ts.contains(&format!("  SIZE: {size},")));
        assert!(ts.contains(&format!("export const RING_COUNT = {RING_COUNT};")));
    }
}
