//! `cargo xtask codegen blob-symbols`: the pinned blob-defined symbol set, written to
//! `specs/hle/idf-5.5.3/blob-symbols.txt`.
//!
//! An image's tripwires are the blob-defined set intersected with the image's symbol table, minus
//! hooked symbols and minus the coexistence allowlist, the set being every defined symbol of the
//! IDF 5.5.3 blob archives. The set is committed and regenerated only when the IDF pin changes, so
//! a checkout without ESP-IDF still builds the right tripwires. The archives' ELF symbol tables
//! are read directly, not through `nm`; the IDF is found only through `IDF_PATH` or
//! `--idf <dir>`, never on `PATH`.
//!
//! Read: the four `esp32c3` blob directories of the radio boundary (Wi-Fi, PHY,
//! coexistence, and the BT controller of `lib_esp32c3_family`). `libopenthread_br.a` and
//! `libble_mesh.a` are not: 802.15.4 is not on this board, and BLE Mesh sits above the controller
//! boundary. The set is each member's **defined global and weak** symbols, the only names a link
//! resolves; locals cannot match across a link and undefined ones are references.
//!
//! The file: a header of `key value` lines (IDF version, archive and member counts, per-archive
//! counts, SHA-256 of the body), a blank line, then one sorted symbol per line. `codegen --check`
//! verifies order, uniqueness, counts and digest without the IDF; `codegen blob-symbols --idf
//! <dir> --check` also re-extracts and compares byte for byte.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use pemu_loader::elf::ElfInfo;
use pemu_loader::symbols::SymBind;
use pemu_loader::{hex, sha256};

/// The generated file, relative to the repository root.
pub const SPEC_PATH: &str = "specs/hle/idf-5.5.3/blob-symbols.txt";

/// The IDF version the list is pinned to.
pub const IDF_VERSION: &str = "v5.5.3";

/// First line of the generated file, the same shape `xtask codegen` uses for generated Rust.
pub const GENERATED_HEADER: &str = "# generated by cargo xtask codegen blob-symbols; do not edit.";

/// Blob directories read, relative to the IDF root (module header).
pub const ARCHIVE_DIRS: &[&str] = &[
    "components/esp_wifi/lib/esp32c3",
    "components/esp_phy/lib/esp32c3",
    "components/esp_coex/lib/esp32c3",
    "components/bt/controller/lib_esp32c3_family/esp32c3",
];

const USAGE: &str = "usage: cargo xtask codegen blob-symbols [--idf <dir>] [--check]";

/// Entry point of `cargo xtask codegen blob-symbols`.
pub fn run(root: &Path, args: &[String]) -> Result<(), String> {
    let mut idf: Option<PathBuf> = None;
    let mut check = false;
    let mut iter = args.iter();
    while let Some(arg) = iter.next() {
        match arg.as_str() {
            "--idf" => {
                let value = iter.next().ok_or(format!("--idf needs a path\n{USAGE}"))?;
                idf = Some(PathBuf::from(value));
            }
            "--check" => check = true,
            "-h" | "--help" => {
                println!("{USAGE}");
                return Ok(());
            }
            other => return Err(format!("unknown argument `{other}`\n{USAGE}")),
        }
    }
    let idf = idf
        .or_else(|| std::env::var_os("IDF_PATH").map(PathBuf::from))
        .ok_or_else(|| format!("no ESP-IDF: pass --idf <dir> or set IDF_PATH\n{USAGE}"))?;
    let rendered = render(&extract(&idf)?);
    let path = root.join(SPEC_PATH);
    let current = std::fs::read_to_string(&path).ok();
    if current.as_deref() == Some(rendered.as_str()) {
        println!("blob-symbols: {SPEC_PATH} is up to date");
        return Ok(());
    }
    if check {
        return Err(format!(
            "{SPEC_PATH} differs from the IDF at {}; run `cargo xtask codegen blob-symbols`",
            idf.display()
        ));
    }
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    std::fs::write(&path, &rendered).map_err(|e| format!("{}: {e}", path.display()))?;
    println!("blob-symbols: wrote {SPEC_PATH}");
    Ok(())
}

/// The IDF-free half, which `cargo xtask codegen --check` runs: the committed file parses, its
/// body is sorted, unique and non-empty, and its counts and digest agree (module header).
pub fn check_committed(root: &Path) -> Result<(), String> {
    let path = root.join(SPEC_PATH);
    let text = std::fs::read_to_string(&path).map_err(|e| {
        format!("cannot read {SPEC_PATH}: {e}; run `cargo xtask codegen blob-symbols`")
    })?;
    let list = parse(&text)?;
    println!(
        "blob-symbols: {SPEC_PATH} pins {} symbol(s) from {} archive(s) of ESP-IDF {}",
        list.symbols.len(),
        list.archives.len(),
        list.idf
    );
    Ok(())
}

/// The pinned list, as read back from the committed file.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlobSymbols {
    /// IDF version the list was extracted from.
    pub idf: String,
    /// Archive file name to how many symbols that archive itself defines, in name order.
    pub archives: BTreeMap<String, usize>,
    /// Archive members read.
    pub members: usize,
    /// The defined global and weak symbols of every archive, sorted and unique.
    pub symbols: Vec<String>,
}

/// Parses the generated file and runs every structural check `--check` makes (module header).
pub fn parse(text: &str) -> Result<BlobSymbols, String> {
    let mut idf = String::new();
    let mut archives = BTreeMap::new();
    let mut members = 0usize;
    let mut declared = 0usize;
    let mut digest = String::new();
    let mut lines = text.lines();
    let first = lines.next().unwrap_or_default();
    if first != GENERATED_HEADER {
        return Err(format!(
            "{SPEC_PATH}: first line is not the generated header"
        ));
    }
    for line in lines.by_ref() {
        if line.is_empty() {
            break;
        }
        if line.starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once(' ')
            .ok_or_else(|| format!("{SPEC_PATH}: header line `{line}` is not `key value`"))?;
        let number = || {
            value
                .parse::<usize>()
                .map_err(|_| format!("{SPEC_PATH}: `{key}` is not a number"))
        };
        match key {
            "idf" => idf = value.to_string(),
            "members" => members = number()?,
            "symbols" => declared = number()?,
            "sha256" => digest = value.to_string(),
            "archive" => {
                let (name, count) = value
                    .split_once(' ')
                    .ok_or_else(|| format!("{SPEC_PATH}: `archive` needs a name and a count"))?;
                let count = count
                    .parse::<usize>()
                    .map_err(|_| format!("{SPEC_PATH}: archive `{name}` count is not a number"))?;
                archives.insert(name.to_string(), count);
            }
            other => return Err(format!("{SPEC_PATH}: unknown header key `{other}`")),
        }
    }
    let symbols: Vec<String> = lines.map(str::to_string).collect();
    if idf != IDF_VERSION {
        return Err(format!(
            "{SPEC_PATH}: pinned to ESP-IDF `{idf}`, and this tree expects `{IDF_VERSION}`"
        ));
    }
    if symbols.is_empty() {
        return Err(format!("{SPEC_PATH}: the symbol list is empty"));
    }
    if symbols.len() != declared {
        return Err(format!(
            "{SPEC_PATH}: the header says {declared} symbol(s) and the body holds {}",
            symbols.len()
        ));
    }
    if archives.is_empty() {
        return Err(format!("{SPEC_PATH}: no archive is named in the header"));
    }
    if members == 0 {
        return Err(format!(
            "{SPEC_PATH}: the header says no archive member was read"
        ));
    }
    for pair in symbols.windows(2) {
        if pair[0] >= pair[1] {
            return Err(format!(
                "{SPEC_PATH}: `{}` and `{}` are out of order or duplicated",
                pair[0], pair[1]
            ));
        }
    }
    let found = hex(&sha256(body(&symbols).as_bytes()));
    if found != digest {
        return Err(format!(
            "{SPEC_PATH}: the header digest is {digest} and the body hashes to {found}; \
             regenerate it with `cargo xtask codegen blob-symbols`"
        ));
    }
    Ok(BlobSymbols {
        idf,
        archives,
        members,
        symbols,
    })
}

/// The body the digest covers: one symbol per line, newline terminated.
fn body(symbols: &[String]) -> String {
    let mut out = String::new();
    for name in symbols {
        out.push_str(name);
        out.push('\n');
    }
    out
}

/// What one extraction found.
pub struct Extracted {
    /// Archive file name to how many symbols that archive itself defines.
    pub archives: BTreeMap<String, usize>,
    /// Archive members read.
    pub members: usize,
    /// The union of every archive's defined global and weak symbols.
    pub symbols: BTreeSet<String>,
}

/// The defined global and weak symbols of one archive, and how many members it holds.
///
/// Every member must parse as an ELF object. A member that does not is refused rather than
/// skipped: its definitions would silently drop out of the tripwire set, and the pinned list
/// would still look complete.
fn archive_symbols(bytes: &[u8]) -> Result<(usize, BTreeSet<String>), String> {
    let mut own = BTreeSet::new();
    let found = members(bytes)?;
    for (index, member) in found.iter().enumerate() {
        let elf = ElfInfo::parse(member).map_err(|e| {
            format!("member {index} is not an ELF object this reader can parse ({e:?})")
        })?;
        for sym in elf.symbols.iter() {
            if sym.is_defined()
                && matches!(sym.bind, SymBind::Global | SymBind::Weak)
                && !sym.name.is_empty()
            {
                own.insert(sym.name.clone());
            }
        }
    }
    Ok((found.len(), own))
}

/// Reads every blob archive under `idf` and returns their defined global and weak symbols.
pub fn extract(idf: &Path) -> Result<Extracted, String> {
    let mut out = Extracted {
        archives: BTreeMap::new(),
        members: 0,
        symbols: BTreeSet::new(),
    };
    for dir in ARCHIVE_DIRS {
        let dir = idf.join(dir);
        let entries =
            std::fs::read_dir(&dir).map_err(|e| format!("cannot read {}: {e}", dir.display()))?;
        let mut files: Vec<PathBuf> = entries
            .filter_map(|entry| entry.ok().map(|e| e.path()))
            .filter(|p| p.extension().is_some_and(|e| e == "a"))
            .collect();
        files.sort();
        for file in files {
            let name = file
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or_default()
                .to_string();
            let bytes = std::fs::read(&file).map_err(|e| format!("{}: {e}", file.display()))?;
            // Counted per archive, not per first appearance: several archives define the same
            // name, and a count that depended on the order they were read in would move when an
            // archive is added.
            let (read, own) =
                archive_symbols(&bytes).map_err(|e| format!("{}: {e}", file.display()))?;
            out.members += read;
            out.archives.insert(name, own.len());
            out.symbols.extend(own);
        }
    }
    if out.symbols.is_empty() {
        return Err(format!(
            "no blob symbol found under {}; is this an ESP-IDF {IDF_VERSION} checkout?",
            idf.display()
        ));
    }
    Ok(out)
}

/// The generated file for one extraction.
pub fn render(found: &Extracted) -> String {
    let symbols: Vec<String> = found.symbols.iter().cloned().collect();
    let body = body(&symbols);
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str(
        "# The blob-defined set: every defined global or weak symbol of the ESP-IDF\n\
         # blob archives of this chip. A machine's tripwires are this set intersected with the\n\
         # image's own symbol table, minus hooked symbols and minus the coexistence allowlist.\n\
         # Regenerated only when the IDF pin changes.\n",
    );
    out.push_str(&format!("idf {IDF_VERSION}\n"));
    out.push_str(&format!("members {}\n", found.members));
    out.push_str(&format!("symbols {}\n", symbols.len()));
    out.push_str(&format!("sha256 {}\n", hex(&sha256(body.as_bytes()))));
    for (name, count) in &found.archives {
        out.push_str(&format!("archive {name} {count}\n"));
    }
    out.push('\n');
    out.push_str(&body);
    out
}

/// The `ar` members of an archive, skipping the symbol table and long-name members.
///
/// The format is the System V one every toolchain writes: an `!<arch>\n` magic, then per member a
/// 60-byte header whose fields are space padded (name 16, mtime 12, uid 6, gid 6, mode 8, size
/// 10, magic 2), the member bytes, and a padding byte when the size is odd. A name of `/` is the
/// symbol table and `//` the long-name table; a name of `/<n>` is an offset into that table, and
/// a plain name ends with `/`. Only the member bytes matter here, so the names are skipped rather
/// than resolved.
fn members(bytes: &[u8]) -> Result<Vec<&[u8]>, String> {
    const MAGIC: &[u8] = b"!<arch>\n";
    const HEADER: usize = 60;
    if !bytes.starts_with(MAGIC) {
        return Err("not an `ar` archive".to_string());
    }
    let mut out = Vec::new();
    let mut at = MAGIC.len();
    while at + HEADER <= bytes.len() {
        let header = &bytes[at..at + HEADER];
        let name = std::str::from_utf8(&header[..16])
            .map_err(|_| "archive member name is not UTF-8".to_string())?
            .trim_end();
        let size: usize = std::str::from_utf8(&header[48..58])
            .map_err(|_| "archive member size is not UTF-8".to_string())?
            .trim()
            .parse()
            .map_err(|_| "archive member size is not a number".to_string())?;
        at += HEADER;
        let end = at
            .checked_add(size)
            .filter(|end| *end <= bytes.len())
            .ok_or_else(|| "archive member runs past the end of the file".to_string())?;
        if name != "/" && name != "//" && name != "/SYM64/" {
            out.push(&bytes[at..end]);
        }
        at = end + (size & 1);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn archive(members: &[(&str, &[u8])]) -> Vec<u8> {
        let mut out = b"!<arch>\n".to_vec();
        for (name, body) in members {
            let header = format!(
                "{:<16}{:<12}{:<6}{:<6}{:<8}{:<10}`\n",
                name,
                0,
                0,
                0,
                644,
                body.len()
            );
            out.extend_from_slice(header.as_bytes());
            out.extend_from_slice(body);
            if body.len() % 2 == 1 {
                out.push(b'\n');
            }
        }
        out
    }

    #[test]
    fn the_ar_reader_skips_the_index_members_and_handles_padding() {
        let bytes = archive(&[
            ("/", b"index".as_slice()),
            ("//", b"names".as_slice()),
            ("a.o/", b"odd".as_slice()),
            ("b.o/", b"even".as_slice()),
        ]);
        let found = members(&bytes).expect("parses");
        assert_eq!(found, [b"odd".as_slice(), b"even".as_slice()]);
    }

    #[test]
    fn a_member_that_is_not_an_elf_object_is_refused_not_skipped() {
        let bytes = archive(&[("a.o/", b"not an object".as_slice())]);
        let err = archive_symbols(&bytes).expect_err("an unreadable member fails the extraction");
        assert!(err.contains("member 0"), "{err}");
    }

    /// The committed list is what the pinned IDF's archives define, byte for byte. Runs where
    /// ESP-IDF v5.5.3 is installed (`IDF_PATH`, else `~/esp/esp-idf-v5.5.3`, as `codegen import`'s
    /// test does) and skips with the reason otherwise.
    #[test]
    fn the_committed_list_regenerates_byte_for_byte_from_the_pinned_idf() {
        let idf = std::env::var_os("IDF_PATH").map(PathBuf::from).or_else(|| {
            std::env::var_os("HOME").map(|home| PathBuf::from(home).join("esp/esp-idf-v5.5.3"))
        });
        let Some(idf) = idf.filter(|dir| dir.is_dir()) else {
            eprintln!(
                "skipped: ESP-IDF is not installed (IDF_PATH unset, ~/esp/esp-idf-v5.5.3 absent)"
            );
            return;
        };
        // `tools/cmake/version.cmake` is where an IDF checkout records its own version.
        let cmake =
            std::fs::read_to_string(idf.join("tools/cmake/version.cmake")).unwrap_or_default();
        let part = |key: &str| {
            cmake.lines().find_map(|line| {
                line.strip_prefix(&format!("set({key} "))
                    .and_then(|rest| rest.strip_suffix(')'))
                    .map(str::to_string)
            })
        };
        let version = format!(
            "v{}.{}.{}",
            part("IDF_VERSION_MAJOR").unwrap_or_default(),
            part("IDF_VERSION_MINOR").unwrap_or_default(),
            part("IDF_VERSION_PATCH").unwrap_or_default()
        );
        if version != IDF_VERSION {
            eprintln!(
                "skipped: the ESP-IDF at {} is `{version}`, not the pinned {IDF_VERSION}",
                idf.display()
            );
            return;
        }
        let root = crate::util::workspace_root();
        let committed = std::fs::read_to_string(root.join(SPEC_PATH)).expect("committed list");
        let regenerated = render(&extract(&idf).expect("the pinned IDF's archives extract"));
        assert!(
            regenerated == committed,
            "{SPEC_PATH} is not what ESP-IDF {IDF_VERSION} defines; run `cargo xtask codegen \
             blob-symbols`"
        );
    }

    #[test]
    fn a_file_that_is_not_an_archive_is_refused() {
        assert!(members(b"\x7fELF").is_err());
    }

    #[test]
    fn a_truncated_member_is_refused() {
        let mut bytes = archive(&[("a.o/", b"1234".as_slice())]);
        bytes.truncate(bytes.len() - 2);
        assert!(members(&bytes).is_err());
    }

    fn extracted(names: &[&str]) -> Extracted {
        Extracted {
            archives: BTreeMap::from([("libpp.a".to_string(), names.len())]),
            members: 3,
            symbols: names.iter().map(|n| (*n).to_string()).collect(),
        }
    }

    #[test]
    fn a_rendered_list_parses_back_into_itself() {
        let found = extracted(&["ppTxPkt", "esp_wifi_init", "phy_close_rf"]);
        let text = render(&found);
        let list = parse(&text).expect("round-trips");
        assert_eq!(list.idf, IDF_VERSION);
        assert_eq!(list.members, 3);
        assert_eq!(list.archives["libpp.a"], 3);
        assert_eq!(
            list.symbols,
            ["esp_wifi_init", "phy_close_rf", "ppTxPkt"],
            "sorted"
        );
        assert!(!text.contains('\r'), "`xtask portable` forbids a CR byte");
    }

    #[test]
    fn an_edited_body_fails_the_digest() {
        let text = render(&extracted(&["ppTxPkt", "esp_wifi_init"]));
        let edited = text.replace("ppTxPkt", "ppTxPk_");
        let err = parse(&edited).expect_err("the digest catches a hand edit");
        assert!(err.contains("hashes to"), "{err}");
    }

    #[test]
    fn an_out_of_order_or_duplicated_body_is_refused() {
        let text = render(&extracted(&["a", "b"]));
        let swapped = text.replace("\na\nb\n", "\nb\na\n");
        assert!(parse(&swapped).is_err());
        let duplicated = text.replace("\na\nb\n", "\na\na\n");
        assert!(parse(&duplicated).is_err());
    }

    #[test]
    fn a_count_that_disagrees_with_the_body_is_refused() {
        let text = render(&extracted(&["a", "b"]));
        let err = parse(&text.replace("symbols 2", "symbols 3")).expect_err("count check");
        assert!(err.contains("the body holds 2"), "{err}");
    }

    #[test]
    fn a_file_without_the_generated_header_is_refused() {
        let text = render(&extracted(&["a"]));
        assert!(parse(text.trim_start_matches(GENERATED_HEADER)).is_err());
    }
}
