//! `cargo xtask codegen`: spec tables and generated sources.
//!
//! - `codegen [--check]` turns `specs/irq-sources.toml`, `specs/c3-registers.csv` and
//!   `specs/blocks/` into `crates/pemu-core/src/irq_source.rs`, `gen/regs_<block>.rs`,
//!   `gen/mod.rs`, `gen/waits.rs`, `gen/classes.rs` and the `docs/fidelity.md` ledger; `--check`
//!   fails on a stale file.
//! - `codegen blob-symbols [--idf <dir>] [--check]` rebuilds `specs/hle/idf-5.5.3/blob-symbols.txt`
//!   from the IDF blob archives; the first form only verifies it.
//! - `codegen import [--idf <dir>] [--check]` rebuilds the CSV and the IRQ table from IDF v5.5.3.
//!   Both are run by hand when an input changes: their inputs live outside the repository, so CI
//!   tiers run only the first form.
//!
//! Generated tests: per block `table_is_consistent`, `fields_decode` and, through `RegStore`,
//! `resets_restore_the_table` and `access_types_behave`; `anchors` checks 13 IDF header resets,
//! the one check not derived from the CSV; `layout` the GDMA and MMU cross-checks. Columns and
//! block schema: `specs/README.md` sections 2, 3. Import rules:
//! - Access (`access.rs`): TRM Glossary types map exactly; any other string is `UNVERIFIED`.
//! - Reset scopes use the terms of IDF `soc/reset_reasons.h`: `System` also resets the RTC
//!   sub-system, `Core` resets the digital system without it. The SENSITIVE lock rule and values
//!   that are no header default are `specs/blocks/` rows.
//! - No readable field layout, so no rows: `iomux` (`io_mux_reg.h`), radio (`nrx_reg.h`), `regi2c`,
//!   `twai` (`twai_struct.h` only, no `twai_reg.h`), crypto (`soc/hwcrypto_reg.h`), and `mmu`,
//!   `dedicated_gpio`, `world_cntl` (a base in `reg_base.h` only).
//! - Header fixes (`idf.rs`), named in `note`: `_S`/`_V` macros beat a bitpos comment
//!   (`usb_serial_jtag_reg.h`, `usb_serial_jtag_struct.h` agrees); `syscon_reg.h` aliases skipped.

mod access;
mod blocks;
mod classes;
mod csv;
mod fidelity;
mod idf;
mod import;
mod import_irq;
mod irq;
mod regs;
#[cfg(test)]
mod tests;
mod waits;

pub use crate::util::workspace_root;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// First line of every generated Rust file.
pub const GENERATED_HEADER: &str = "//! generated by cargo xtask codegen; do not edit.";

/// Entry point of `cargo xtask codegen`.
pub fn run(args: &[String]) -> Result<(), String> {
    let root = workspace_root();
    match args.first().map(String::as_str) {
        Some("import") => import::run(&root, &args[1..]),
        // Regenerated by hand when the IDF pin changes.
        Some("blob-symbols") => crate::blob_symbols::run(&root, &args[1..]),
        _ => {
            let check = parse_check_only(args)?;
            generate(&root, check)
        }
    }
}

fn parse_check_only(args: &[String]) -> Result<bool, String> {
    let mut check = false;
    for arg in args {
        match arg.as_str() {
            "--check" => check = true,
            other => return Err(format!("unknown argument `{other}`")),
        }
    }
    Ok(check)
}

/// Renders every generated file from `specs/` and writes it, or compares it with `--check`.
fn generate(root: &Path, check: bool) -> Result<(), String> {
    let mut outputs = Vec::new();

    let toml_path = root.join(irq::SPEC_PATH);
    let text = fs::read_to_string(&toml_path)
        .map_err(|e| format!("cannot read {}: {e}", toml_path.display()))?;
    let sources = irq::parse(&text)?;
    outputs.push((
        PathBuf::from(irq::OUTPUT_PATH),
        format_rust(root, &irq::render(&sources))?,
    ));

    let rows = check_register_table(root)?;
    let mut blocks = regs::group(&rows)?;
    let specs = blocks::load(root)?;
    blocks::check(&specs, &blocks, &blocks::device_rows(root)?)?;
    blocks::apply(&mut blocks, &specs)?;
    let blocks = blocks;
    let dir = Path::new(regs::OUTPUT_DIR);
    for block in &blocks {
        outputs.push((
            dir.join(format!("{}.rs", block.module())),
            format_rust(root, &regs::render_block(block))?,
        ));
    }
    outputs.push((
        dir.join("mod.rs"),
        format_rust(root, &regs::render_mod(&blocks))?,
    ));
    outputs.push((
        PathBuf::from(waits::OUTPUT_PATH),
        format_rust(root, &waits::render(&specs))?,
    ));
    outputs.push((
        PathBuf::from(classes::OUTPUT_PATH),
        format_rust(root, &classes::render(&specs)?)?,
    ));
    // The fidelity ledger is an aggregate build output that `.gitignore` lists, so `--check`
    // compares it only when a previous run left one behind.
    let ledger = PathBuf::from(fidelity::OUTPUT_PATH);
    if !check || root.join(&ledger).exists() {
        outputs.push((ledger, fidelity::render(&specs, &blocks)));
    }

    // The blob-symbol list comes from ESP-IDF, not `specs/`, so it is checked, not rendered.
    crate::blob_symbols::check_committed(root)?;

    check_no_stale_tables(root, &outputs)?;
    write_or_check(root, &outputs, check)
}

/// Fails when `crates/pemu-soc-c3/src/gen/` holds a Rust file that codegen does not generate any
/// more, so `--check` covers every file of the directory.
fn check_no_stale_tables(root: &Path, outputs: &[(PathBuf, String)]) -> Result<(), String> {
    let dir = root.join(regs::OUTPUT_DIR);
    let entries = match fs::read_dir(&dir) {
        Ok(entries) => entries,
        Err(_) => return Ok(()),
    };
    let mut stale = Vec::new();
    for entry in entries {
        let name = entry
            .map_err(|e| format!("{}: {e}", dir.display()))?
            .file_name();
        let rel = Path::new(regs::OUTPUT_DIR).join(&name);
        if Path::new(&name).extension().is_some_and(|e| e == "rs")
            && !outputs.iter().any(|(path, _)| *path == rel)
        {
            stale.push(rel.display().to_string());
        }
    }
    if stale.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "generated file(s) no longer produced by codegen, delete them: {}",
            stale.join(", ")
        ))
    }
}

/// Reads `specs/c3-registers.csv` and checks it: rows parse, blocks are imported blocks, registers
/// lie inside the block window, and blocks appear in `c3_devices!` order.
fn check_register_table(root: &Path) -> Result<Vec<csv::Row>, String> {
    let path = root.join(csv::SPEC_PATH);
    let text =
        fs::read_to_string(&path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    let rows = csv::parse(&text)?;
    let mut last = 0;
    for r in &rows {
        let pos = import::BLOCKS
            .iter()
            .position(|b| b.0 == r.block)
            .ok_or_else(|| format!("{}: unknown block `{}`", csv::SPEC_PATH, r.block))?;
        if pos < last {
            return Err(format!(
                "{}: block `{}` out of order",
                csv::SPEC_PATH,
                r.block
            ));
        }
        last = pos;
        if !r.offset.is_multiple_of(4) || r.offset + 4 > import::BLOCKS[pos].1 {
            return Err(format!(
                "{}: {}.{} outside the block window",
                csv::SPEC_PATH,
                r.register,
                r.field
            ));
        }
    }
    Ok(rows)
}

/// Writes each `(relative path, contents)` pair, or with `check` fails listing the files whose
/// contents differ.
pub fn write_or_check(
    root: &Path,
    outputs: &[(PathBuf, String)],
    check: bool,
) -> Result<(), String> {
    let mut stale = Vec::new();
    let mut written = 0;
    for (rel, contents) in outputs {
        let path = root.join(rel);
        let current = fs::read_to_string(&path).ok();
        if current.as_deref() == Some(contents.as_str()) {
            continue;
        }
        if check {
            stale.push(rel.display().to_string());
        } else {
            if let Some(dir) = path.parent() {
                fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
            }
            fs::write(&path, contents).map_err(|e| format!("{}: {e}", path.display()))?;
            println!("codegen: wrote {}", rel.display());
            written += 1;
        }
    }
    if stale.is_empty() {
        let fresh = outputs.len() - written;
        if check {
            println!("codegen: {fresh} file(s) up to date");
        } else {
            println!("codegen: {written} file(s) written, {fresh} file(s) already up to date");
        }
        Ok(())
    } else {
        Err(format!(
            "generated file(s) out of date, run `cargo xtask codegen`: {}",
            stale.join(", ")
        ))
    }
}

/// Formats Rust source with the workspace `rustfmt` configuration (edition 2024).
pub fn format_rust(root: &Path, source: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout", "--quiet"])
        .current_dir(root)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("cannot run rustfmt: {e}"))?;
    child
        .stdin
        .take()
        .ok_or("rustfmt stdin unavailable")?
        .write_all(source.as_bytes())
        .map_err(|e| format!("rustfmt stdin: {e}"))?;
    let out = child
        .wait_with_output()
        .map_err(|e| format!("rustfmt: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "rustfmt failed: {}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    String::from_utf8(out.stdout).map_err(|e| format!("rustfmt output: {e}"))
}
