//! The Markdown surfaces: `docs/commands/<name>.md`, `docs/commands/index.md` and
//! `docs/errors.md`.
//!
//! Host availability is a column read from `pemu_api::host_support::TABLE`, never a filter, so
//! the committed text is byte-identical on macOS, on Windows and in a browser build.

use pemu_api::error::{self, ErrorCode};
use pemu_api::spec::CapsGroup;
use serde_json::Value;

use super::mcp;
use super::model::{Command, HOSTS, annotation_names};

/// First line of every generated Markdown file.
pub const HEADER: &str = "<!-- generated by `cargo xtask docs`; do not edit. -->";

/// `yes` or `no` in a host column.
fn yes_no(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}

/// `docs/commands/<name>.md`: the reference page of one command.
pub fn command_page(command: &Command) -> String {
    let spec = command.spec;
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n");
    out.push_str(&format!("# `passportsim {}`\n\n", spec.name));
    out.push_str(&format!("{}\n\n", spec.summary));

    out.push_str("| Property | Value |\n|---|---|\n");
    out.push_str(&format!("| Caps group | `{}` |\n", spec.group.caps_name()));
    out.push_str(&format!("| MCP tool | `{}` |\n", command.mcp_tool()));
    out.push_str(&format!("| HTTP route | `{}` |\n", command.http_route()));
    out.push_str(&format!(
        "| Scenario step | {} |\n",
        spec.scenario_step
            .map(|s| format!("`{s}`"))
            .unwrap_or_else(|| "none".to_string())
    ));
    out.push_str(&format!(
        "| CLI aliases | {} |\n",
        list_or_none(spec.cli.aliases)
    ));
    out.push_str(&format!(
        "| Annotations | {} |\n",
        list_or_none(&annotation_names(spec))
    ));
    out.push('\n');

    out.push_str("## Hosts\n\n");
    out.push_str(
        "The matrix below is the full one; this page is byte-identical on every host.\n\n",
    );
    out.push_str("| macOS | Windows | Browser |\n|---|---|---|\n");
    out.push_str(&format!(
        "| {} | {} | {} |\n",
        yes_no(command.hosts.macos),
        yes_no(command.hosts.windows),
        yes_no(command.hosts.browser)
    ));
    if let Some(hint) = pemu_api::host_support::hint(spec.name) {
        out.push_str(&format!(
            "\nWhere it does not run, `E_HOST_UNSUPPORTED` names the alternative: {hint}\n"
        ));
    }
    out.push('\n');

    out.push_str("## Synopsis\n\n");
    out.push_str("```text\n");
    out.push_str(&synopsis(command));
    out.push_str("\n```\n\n");

    out.push_str("## Arguments\n\n");
    out.push_str(&arguments_table(command));
    out.push_str(&format!(
        "\nInput schema: [`docs/schema/commands/{}.input.json`](../schema/commands/{}.input.json).\n\n",
        spec.name, spec.name
    ));

    out.push_str("## Output\n\n");
    out.push_str(&format!(
        "Output schema: [`docs/schema/commands/{}.output.json`](../schema/commands/{}.output.json).\n",
        spec.name, spec.name
    ));
    out.push_str(&format!(
        "TypeScript types: `web/src/gen/commands/{}.d.ts` (`{}`, `{}`).\n\n",
        spec.name,
        command.ts_args(),
        command.ts_result()
    ));

    out.push_str("## Errors\n\n");
    if spec.errors.is_empty() {
        out.push_str("This command registers no error code of its own.\n\n");
    } else {
        out.push_str("| Code | Number |\n|---|---|\n");
        let mut codes: Vec<ErrorCode> = spec.errors.to_vec();
        codes.sort_by_key(|code| code.number);
        for code in codes {
            out.push_str(&format!("| `{}` | {} |\n", code.name, code.number));
        }
        out.push_str("\nEvery code is listed in [`docs/errors.md`](../errors.md).\n\n");
    }

    out.push_str("## Examples\n\n");
    for example in spec.examples {
        out.push_str(&format!("### {}\n\n", example.title));
        out.push_str(&example_blocks(command, example.args));
    }
    out
}

/// `skills/passportsim/references/commands/<name>.md`: the page of one command as the skill
/// carries it. It is [`command_page`] without the links that leave the skill directory (schemas,
/// TypeScript types, the repository's error page) and without the HTTP route, so an installed
/// skill is complete on its own.
pub fn skill_command_page(command: &Command) -> String {
    let spec = command.spec;
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n");
    out.push_str(&format!("# `passportsim {}`\n\n", spec.name));
    out.push_str(&format!("{}\n\n", spec.summary));
    out.push_str("| MCP tool | Scenario step | macOS | Windows | Browser |\n");
    out.push_str("|---|---|---|---|---|\n");
    out.push_str(&format!(
        "| `{}` | {} | {} | {} | {} |\n",
        command.mcp_tool(),
        spec.scenario_step
            .map(|s| format!("`{s}`"))
            .unwrap_or_else(|| "none".to_string()),
        yes_no(command.hosts.macos),
        yes_no(command.hosts.windows),
        yes_no(command.hosts.browser)
    ));
    if let Some(hint) = pemu_api::host_support::hint(spec.name) {
        out.push_str(&format!(
            "\nWhere it does not run, `E_HOST_UNSUPPORTED` names the alternative: {hint}\n"
        ));
    }
    out.push('\n');

    out.push_str("## Synopsis\n\n```text\n");
    out.push_str(&synopsis(command));
    out.push_str("\n```\n\n");

    out.push_str("## Arguments\n\n");
    out.push_str(&arguments_table(command));
    out.push('\n');

    out.push_str("## Errors\n\n");
    if spec.errors.is_empty() {
        out.push_str("This command registers no error code of its own.\n\n");
    } else {
        let mut codes: Vec<ErrorCode> = spec.errors.to_vec();
        codes.sort_by_key(|code| code.number);
        let names: Vec<String> = codes
            .iter()
            .map(|code| format!("`{}` ({})", code.name, code.number))
            .collect();
        out.push_str(&names.join(", "));
        out.push_str(". What each means: [errors.md](../errors.md).\n\n");
    }

    out.push_str("## Examples\n\n");
    for example in spec.examples {
        out.push_str(&format!("### {}\n\n", example.title));
        out.push_str(&example_blocks(command, example.args));
    }
    out
}

/// `skills/passportsim/references/commands.md`: the command list the skill reads first.
pub fn skill_index_page(commands: &[Command]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n# Commands\n\n");
    out.push_str(
        "Every command of the registry this skill was generated from. `passportsim --help` lists \
         the commands of the binary you have and `passportsim <command> --help` prints one \
         command's synopsis and arguments; where they differ from these pages, the binary is \
         right. The MCP server (`passportsim mcp`) serves the core tools; `--caps` adds the \
         other groups.\n\n",
    );
    out.push_str(
        "| Command | MCP tool | Group | macOS | Windows | Browser | Summary |\n\
         |---|---|---|---|---|---|---|\n",
    );
    for command in commands {
        out.push_str(&format!(
            "| [`{}`](commands/{}.md) | `{}` | `{}` | {} | {} | {} | {} |\n",
            command.spec.name,
            command.spec.name,
            command.mcp_tool(),
            command.spec.group.caps_name(),
            yes_no(command.hosts.macos),
            yes_no(command.hosts.windows),
            yes_no(command.hosts.browser),
            command.spec.summary
        ));
    }
    if commands.is_empty() {
        out.push_str("| _(no command is registered yet)_ | | | | | | |\n");
    }
    out
}

/// `skills/passportsim/references/errors.md`: every registered code with its meaning.
pub fn skill_errors_page() -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n# Error codes\n\n");
    out.push_str(
        "A failed command returns one typed envelope: `code`, `number`, `message`, `vt_us` (the \
         virtual time), `retryable`, an optional `hint`, and `detail`, `serial_tail` and \
         `backtrace` where they apply. With `--output json` it is that JSON object; as text it is \
         the code, the message and the hint. Quote the code and follow the hint.\n\n",
    );
    out.push_str("| Code | Number | Group | Meaning |\n|---|---:|---|---|\n");
    let mut codes = error::registered_error_codes();
    codes.sort_by_key(|code| code.number);
    codes.dedup_by_key(|code| code.number);
    for code in codes {
        let group = code
            .group()
            .map(|group| format!("`{}`", group.caps_name()))
            .unwrap_or_default();
        out.push_str(&format!(
            "| `{}` | {} | {group} | {} |\n",
            code.name,
            code.number,
            one_line(code.meaning())
        ));
    }
    out
}

/// A comma-separated list of backticked names, or `none`.
fn list_or_none(items: &[&str]) -> String {
    if items.is_empty() {
        "none".to_string()
    } else {
        items
            .iter()
            .map(|item| format!("`{item}`"))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

/// How the CLI carries one top-level input property: top-level schema properties become flags;
/// nested objects use `--json @file` or `--json -` (stdin), the documented forms.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Form {
    /// Listed in `cli.positional`: a bare argument in its declared order.
    Positional,
    /// A boolean: the bare `--flag`, which takes no value.
    Switch,
    /// A scalar: `--flag <VALUE>`.
    Value,
    /// An object or an array: **not** a flag. It travels inside the `--json` document, because a
    /// nested value has no portable argv spelling.
    Json,
}

/// The [`Form`] of one property, resolving `$ref` into the document's `$defs` (the one reference
/// form `schemars` 1.2 emits for our types), so an aliased enum stays a flag.
fn form_of(schema: &Value, defs: Option<&serde_json::Map<String, Value>>) -> Form {
    form_at(schema, defs, 0)
}

/// [`form_of`] with the reference budget that makes a recursive `$defs` chain terminate.
fn form_at(schema: &Value, defs: Option<&serde_json::Map<String, Value>>, hops: usize) -> Form {
    if let Some(Value::String(reference)) = schema.get("$ref") {
        // A named type whose body is in this document is classified by that body; one that cannot
        // be resolved, and a chain that does not end, may be an object, so it travels in the JSON
        // document rather than becoming a flag that would not work.
        if hops >= 8 {
            return Form::Json;
        }
        let target = reference
            .strip_prefix("#/$defs/")
            .and_then(|name| defs.and_then(|defs| defs.get(name)));
        return match target {
            Some(target) => form_at(target, defs, hops + 1),
            None => Form::Json,
        };
    }
    if let Some(Value::Array(values)) = schema.get("enum") {
        return if values
            .iter()
            .all(|value| !value.is_object() && !value.is_array())
        {
            Form::Value
        } else {
            Form::Json
        };
    }
    if let Some(value) = schema.get("const") {
        return if value.is_object() || value.is_array() {
            Form::Json
        } else {
            Form::Value
        };
    }
    for key in ["anyOf", "oneOf", "allOf"] {
        if let Some(Value::Array(branches)) = schema.get(key) {
            let forms: Vec<Form> = branches
                .iter()
                .map(|branch| form_at(branch, defs, hops + 1))
                .collect();
            if forms.contains(&Form::Json) {
                return Form::Json;
            }
            return if forms.iter().all(|form| *form == Form::Switch) {
                Form::Switch
            } else {
                Form::Value
            };
        }
    }
    // `null` is dropped: an optional scalar is still a scalar flag.
    let names: Vec<&str> = match schema.get("type") {
        Some(Value::String(one)) => vec![one.as_str()],
        Some(Value::Array(many)) => many.iter().filter_map(Value::as_str).collect(),
        // A property with no `type` at all could be an object, so it is not published as a flag.
        _ => return Form::Json,
    };
    let names: Vec<&str> = names.into_iter().filter(|name| *name != "null").collect();
    if names
        .iter()
        .any(|name| *name == "object" || *name == "array")
    {
        return Form::Json;
    }
    if !names.is_empty() && names.iter().all(|name| *name == "boolean") {
        return Form::Switch;
    }
    if names.is_empty() {
        Form::Json
    } else {
        Form::Value
    }
}

/// Every top-level input property with its [`Form`] and whether the schema requires it, in schema
/// order, with the `$defs` of the same document for `$ref` resolution.
fn forms(command: &Command, schema: &Value) -> Vec<(String, Form, bool)> {
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|list| list.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let defs = schema.get("$defs").and_then(Value::as_object);
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        return Vec::new();
    };
    properties
        .iter()
        .map(|(name, property)| {
            let form = if command.spec.cli.positional.contains(&name.as_str()) {
                Form::Positional
            } else {
                form_of(property, defs)
            };
            (name.clone(), form, required.contains(&name.as_str()))
        })
        .collect()
}

/// The CLI usage line of a command: `bin_name("passportsim")`, the `cli.positional` arguments in
/// their declared order, then every other top-level input property in its [`Form`], optional ones
/// in brackets.
///
/// An object or array property is never a flag: it travels in `--json @file` or `--json -`, which
/// becomes the required form as soon as one such property is required. The `pemu-cli` clap tree
/// must produce this shape; its `--help` snapshot test compares the two.
fn synopsis(command: &Command) -> String {
    let spec = command.spec;
    let schema = (spec.input_schema)().to_value();
    let forms = forms(command, &schema);
    let required_of = |wanted: &str| {
        forms
            .iter()
            .find(|(name, _, _)| name == wanted)
            .is_some_and(|(_, _, required)| *required)
    };
    let mut line = format!("passportsim {}", spec.name);
    for name in spec.cli.positional {
        if required_of(name) {
            line.push_str(&format!(" <{name}>"));
        } else {
            line.push_str(&format!(" [{name}]"));
        }
    }
    let mut json_required = false;
    for (name, form, required) in &forms {
        let flag = match form {
            // Already placed above, in the declared order of `cli.positional`.
            Form::Positional => continue,
            Form::Json => {
                json_required |= *required;
                continue;
            }
            Form::Switch => format!("--{}", name.replace('_', "-")),
            Form::Value => format!("--{} <{}>", name.replace('_', "-"), name.to_uppercase()),
        };
        if *required {
            line.push_str(&format!(" {flag}"));
        } else {
            line.push_str(&format!(" [{flag}]"));
        }
    }
    if json_required {
        line.push_str(" --json <@file|->");
    } else {
        line.push_str(" [--json <@file|->]");
    }
    line
}

/// The top-level properties of the input schema as the CLI sees them: top-level schema properties
/// become flags, `cli.positional` ones become positional arguments.
fn arguments_table(command: &Command) -> String {
    let schema = (command.spec.input_schema)().to_value();
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        return "This command takes no declared arguments; its input schema accepts any JSON \
                object.\n"
            .to_string();
    };
    if properties.is_empty() {
        return "This command takes no arguments.\n".to_string();
    }
    let forms = forms(command, &schema);
    let mut out = String::from(
        "| Argument | Form | Type | Required | Description |\n|---|---|---|---|---|\n",
    );
    for (name, form, required) in &forms {
        let Some(property) = properties.get(name) else {
            continue;
        };
        let form = match form {
            Form::Positional => format!("`<{name}>`"),
            Form::Switch => format!("`--{}`", name.replace('_', "-")),
            Form::Value => format!("`--{} <{}>`", name.replace('_', "-"), name.to_uppercase()),
            // A nested value has no flag spelling, it travels in the JSON document.
            Form::Json => "carried by `--json`".to_string(),
        };
        out.push_str(&format!(
            "| `{name}` | {form} | {} | {} | {} |\n",
            schema_type(property),
            yes_no(*required),
            one_line(property.get("description").and_then(Value::as_str))
        ));
    }
    out.push_str(
        "\nA nested object or array is passed as one JSON document with `--json @<file>` or \
         `--json -`; it has no flag of its own.\n",
    );
    out
}

/// A short type name for the arguments table.
fn schema_type(schema: &Value) -> String {
    if let Some(Value::String(reference)) = schema.get("$ref") {
        return format!(
            "`{}`",
            reference.strip_prefix("#/$defs/").unwrap_or(reference)
        );
    }
    if let Some(Value::Array(values)) = schema.get("enum") {
        let names: Vec<String> = values
            .iter()
            .map(|value| format!("`{}`", compact(value)))
            .collect();
        return names.join(" \\| ");
    }
    // An array's element type is what a caller has to get right, and for `inspect`'s `what` it is
    // the only place the section names appear at all. Render it when the items say something more
    // than "object": `array` of `"tasks"` \| ... rather than a bare `array`.
    if schema.get("type").and_then(Value::as_str) == Some("array")
        && let Some(items) = schema.get("items")
    {
        let inner = schema_type(items);
        if inner != "`object`" && inner != "`any`" {
            return format!("`array` of {inner}");
        }
    }
    match schema.get("type") {
        Some(Value::String(one)) => format!("`{one}`"),
        Some(Value::Array(many)) => many
            .iter()
            .filter_map(Value::as_str)
            .map(|one| format!("`{one}`"))
            .collect::<Vec<_>>()
            .join(" \\| "),
        _ if schema.get("anyOf").is_some() || schema.get("oneOf").is_some() => {
            "`union`".to_string()
        }
        _ => "`any`".to_string(),
    }
}

/// A description collapsed to one line, with table pipes escaped, or `-`.
fn one_line(text: Option<&str>) -> String {
    match text {
        Some(text) => {
            let joined = text.split_whitespace().collect::<Vec<_>>().join(" ");
            if joined.is_empty() {
                "-".to_string()
            } else {
                joined.replace('|', "\\|")
            }
        }
        None => "-".to_string(),
    }
}

fn compact(value: &Value) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "?".to_string())
}

/// One example rendered per shell: the `sh` form and the PowerShell form of the same
/// argv, both passing the arguments on standard input, which is the documented portable form
/// because `cmd.exe` has no single quotes and PowerShell 5.1 strips embedded double quotes.
fn example_blocks(command: &Command, args: &str) -> String {
    let parsed: Value = serde_json::from_str(args).unwrap_or(Value::Null);
    let pretty = serde_json::to_string_pretty(&parsed).unwrap_or_else(|_| args.to_string());
    let name = command.spec.name;
    let mut out = String::new();
    out.push_str("```sh\n");
    out.push_str(&format!("passportsim {name} --json - <<'JSON'\n"));
    out.push_str(&pretty);
    out.push_str("\nJSON\n```\n\n");
    out.push_str("```powershell\n");
    out.push_str("@'\n");
    out.push_str(&pretty);
    out.push_str(&format!("\n'@ | passportsim {name} --json -\n"));
    out.push_str("```\n\n");
    out
}

/// `docs/commands/index.md`: the command table, the HTTP route table and the MCP tool list.
///
/// An aggregate build output, not committed.
pub fn index_page(commands: &[Command]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n# Commands\n\n");
    out.push_str(
        "Every surface is generated from one command registry. The host columns are the full \
         matrix of `pemu_api::host_support::TABLE`, so this file is identical on every host.\n\n",
    );

    out.push_str(
        "| Command | Group | macOS | Windows | Browser | Summary |\n|---|---|---|---|---|---|\n",
    );
    for command in commands {
        out.push_str(&format!(
            "| [`{}`]({}.md) | `{}` | {} | {} | {} | {} |\n",
            command.spec.name,
            command.spec.name,
            command.spec.group.caps_name(),
            yes_no(command.hosts.macos),
            yes_no(command.hosts.windows),
            yes_no(command.hosts.browser),
            command.spec.summary
        ));
    }
    if commands.is_empty() {
        out.push_str("| _(no command is registered yet)_ | | | | | |\n");
    }
    out.push('\n');

    out.push_str("## HTTP routes\n\n");
    out.push_str("| Route | Command |\n|---|---|\n");
    for command in commands {
        out.push_str(&format!(
            "| `{}` | `{}` |\n",
            command.http_route(),
            command.spec.name
        ));
    }
    for (route, what) in GET_ALIASES {
        out.push_str(&format!("| `{route}` | {what} |\n"));
    }
    out.push('\n');

    out.push_str("## MCP tools\n\n");
    out.push_str(
        "`tools/list` is filtered by the enabled caps groups at run time; the list below is the \
         whole registry. `xtask mcp-size` guards the core budget.\n\n",
    );
    out.push_str(
        "| Tool | Group | readOnlyHint | destructiveHint | idempotentHint | openWorldHint | Hosts | Bytes |\n\
         |---|---|---|---|---|---|---|---:|\n",
    );
    for command in commands {
        let a = command.spec.annotations;
        let hosts: Vec<&str> = HOSTS
            .iter()
            .filter(|host| command.runs_on(**host))
            .map(|host| host.as_str())
            .collect();
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} | {} | {} | {} | {} |\n",
            command.mcp_tool(),
            command.spec.group.caps_name(),
            yes_no(a.read_only),
            yes_no(a.destructive),
            yes_no(a.idempotent),
            yes_no(command.spec.group == CapsGroup::Device),
            if hosts.is_empty() {
                "none".to_string()
            } else {
                hosts.join(", ")
            },
            mcp::tool_bytes(command)
        ));
    }
    let core: Vec<Command> = commands
        .iter()
        .copied()
        .filter(|command| command.spec.group == CapsGroup::Core)
        .collect();
    out.push_str(&format!(
        "\nCore `tools/list` payload: {} bytes of {}.\n\n",
        mcp::list_bytes(&core),
        mcp::CORE_BUDGET_BYTES
    ));

    out.push_str("## Scenario steps\n\n");
    let steps: Vec<&Command> = commands
        .iter()
        .filter(|command| command.spec.scenario_step.is_some())
        .collect();
    if steps.is_empty() {
        out.push_str("No registered command claims a scenario step yet.\n");
    } else {
        out.push_str("| Step | Command |\n|---|---|\n");
        for command in steps {
            out.push_str(&format!(
                "| `{}` | `{}` |\n",
                command.spec.scenario_step.unwrap_or_default(),
                command.spec.name
            ));
        }
    }
    out
}

/// The GET aliases, which are routes of the server rather than of a command.
const GET_ALIASES: &[(&str, &str)] = &[
    ("GET /v1/instances/{id}/screen.png", "alias of `screenshot`"),
    ("GET /v1/instances/{id}/serial.log", "alias of `serial`"),
    (
        "GET /v1/instances/{id}/events.ndjson",
        "the instance event stream",
    ),
];

/// `docs/errors.md`: every registered error code by group range.
///
/// An aggregate build output, not committed.
pub fn errors_page(commands: &[Command]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n# Error codes\n\n");
    out.push_str(
        "Every command failure is a typed envelope: a registered code, a message, \
         the virtual time, a retryable flag and an optional hint. Codes are registered per caps \
         group, each group holding one number range; a shipped name and number never change or \
         get reused.\n\n",
    );
    out.push_str(
        "The envelope schema is [`docs/schema/error@1.json`](schema/error@1.json). The wasm ABI \
         reports the number as its result status, and 0 means success, so 0 is not a code.\n\n",
    );

    for group in CapsGroup::ALL {
        let range = group.error_range();
        out.push_str(&format!(
            "## `{}` ({}..={})\n\n",
            group.caps_name(),
            range.start(),
            range.end()
        ));
        let mut codes: Vec<ErrorCode> = error::registered_error_codes()
            .into_iter()
            .filter(|code| code.group() == Some(group))
            .collect();
        codes.sort_by_key(|code| code.number);
        codes.dedup_by_key(|code| code.number);
        if codes.is_empty() {
            out.push_str("No code is registered in this range yet.\n\n");
            continue;
        }
        out.push_str("| Code | Number | Meaning | Registered by |\n|---|---:|---|---|\n");
        for code in codes {
            let mut users: Vec<&str> = commands
                .iter()
                .filter(|command| command.spec.errors.contains(&code))
                .map(|command| command.spec.name)
                .collect();
            users.sort_unstable();
            users.dedup();
            let by = if users.is_empty() {
                "pre-registered".to_string()
            } else {
                users
                    .iter()
                    .map(|name| format!("`{name}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            // The sentence is `pemu_api::error`'s, beside the number, so this file cannot drift
            // from the registry it renders (the `error_codes!` table is the source of truth).
            let meaning = one_line(code.meaning());
            out.push_str(&format!(
                "| `{}` | {} | {meaning} | {by} |\n",
                code.name, code.number
            ));
        }
        out.push('\n');
    }
    out
}
