//! TypeScript declarations for the browser surface.
//!
//! `web/src/gen/commands/<command>.d.ts` is a per-item generated file and committed;
//! `web/src/gen/index.d.ts` is the aggregate build output that types
//! `passportEmu.call(name, args)` and is not committed. Both are rendered from the same JSON
//! Schemas the CLI, MCP and HTTP surfaces use, so a type in the browser cannot drift from the
//! schema an agent sees.
//!
//! The translated subset is the one `schemars` 1.2 emits for our argument types; it is the same
//! subset [`super::validate`] checks. An unrecognised schema becomes `unknown`, which is always
//! sound and never silently wrong. An object that declares no member and nothing constrains
//! (`{"type": "object"}`) is `Record<string, unknown>` for the same reason; only an explicit
//! `additionalProperties: false` with no `properties` is the empty `Record<string, never>`.

use std::collections::BTreeMap;

use serde_json::{Map, Value};

use super::model::Command;

/// First line of every generated TypeScript file.
pub const HEADER: &str = "// generated by `cargo xtask docs`; do not edit.";

/// The named types of one schema document, by `$defs` name.
type Defs = Map<String, Value>;

/// `web/src/gen/commands/<command>.d.ts`: the argument and result types of one command.
pub fn command_module(command: &Command) -> Result<String, String> {
    let input = (command.spec.input_schema)().to_value();
    let output = (command.spec.output_schema)().to_value();
    let defs = merged_defs(command.spec.name, &input, &output)?;

    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(&format!(
        "// Command `{}` ({} group): {}\n\n",
        command.spec.name,
        command.spec.group.caps_name(),
        command.spec.summary
    ));
    for (name, schema) in &defs {
        out.push_str(&named_type(name, schema, &defs));
    }
    out.push_str(&named_type(&command.ts_args(), &input, &defs));
    out.push_str(&named_type(&command.ts_result(), &output, &defs));
    Ok(out)
}

/// `web/src/gen/index.d.ts`: the map every browser call (`passportEmu.call`) is typed through.
pub fn index_module(commands: &[Command]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str("// Aggregate build output: never committed.\n\n");
    for command in commands {
        out.push_str(&format!(
            "import type {{ {}, {} }} from \"./commands/{}\";\n",
            command.ts_args(),
            command.ts_result(),
            command.spec.name
        ));
    }
    if !commands.is_empty() {
        out.push('\n');
        for command in commands {
            out.push_str(&format!(
                "export type {{ {}, {} }};\n",
                command.ts_args(),
                command.ts_result()
            ));
        }
        out.push('\n');
    }
    out.push_str("/** Every registered command, by name. */\n");
    out.push_str("export interface CommandMap {\n");
    for command in commands {
        out.push_str(&format!(
            "  {}: {{ args: {}; result: {} }};\n",
            command.spec.name,
            command.ts_args(),
            command.ts_result()
        ));
    }
    if commands.is_empty() {
        out.push_str("  // no command is registered yet\n");
    }
    out.push_str("}\n\n");
    out.push_str("/** `passportEmu.call(name, args)`. */\n");
    out.push_str("export declare function call<K extends keyof CommandMap>(\n");
    out.push_str("  name: K,\n");
    out.push_str("  args: CommandMap[K][\"args\"],\n");
    out.push_str("): Promise<CommandMap[K][\"result\"]>;\n");
    out
}

/// The `$defs` of both schemas of one command under one name space.
///
/// A name defined by both with different bodies would make the module ambiguous; because both
/// come from one `schemars` generator over one crate, that means two distinct Rust types share a
/// name, which is a command-authoring problem, so it is an error rather than a silent rename.
fn merged_defs(command: &str, input: &Value, output: &Value) -> Result<Defs, String> {
    let mut merged = Defs::new();
    for schema in [input, output] {
        let Some(defs) = schema.get("$defs").and_then(Value::as_object) else {
            continue;
        };
        for (name, body) in defs {
            match merged.get(name) {
                Some(existing) if existing != body => {
                    return Err(format!(
                        "command {command}: `$defs` name {name:?} has two different definitions; \
                         rename one of the Rust types"
                    ));
                }
                _ => {
                    merged.insert(name.clone(), body.clone());
                }
            }
        }
    }
    Ok(merged)
}

/// `export type <name> = <body>;`, with the schema description as a doc comment.
fn named_type(name: &str, schema: &Value, defs: &Defs) -> String {
    let mut out = String::new();
    if let Some(doc) = description(schema) {
        out.push_str(&format!("/** {doc} */\n"));
    }
    out.push_str(&format!(
        "export type {} = {};\n\n",
        ident(name),
        ts_type(schema, defs, 0)
    ));
    out
}

/// A `$defs` key or a command name as a TypeScript identifier.
fn ident(name: &str) -> String {
    let mut out: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// The schema `description`, collapsed to one line so it fits a `/** */` comment.
fn description(schema: &Value) -> Option<String> {
    let text = schema.get("description")?.as_str()?;
    let one_line = text.split_whitespace().collect::<Vec<_>>().join(" ");
    if one_line.is_empty() {
        None
    } else {
        Some(one_line.replace("*/", "*\\/"))
    }
}

/// The TypeScript type of one schema. `depth` is the current indentation level of object members.
fn ts_type(schema: &Value, defs: &Defs, depth: usize) -> String {
    let map = match schema {
        Value::Bool(true) => return "unknown".to_string(),
        Value::Bool(false) => return "never".to_string(),
        Value::Object(map) => map,
        _ => return "unknown".to_string(),
    };

    if let Some(Value::String(reference)) = map.get("$ref") {
        return match reference.strip_prefix("#/$defs/") {
            Some(name) => ident(name),
            None => "unknown".to_string(),
        };
    }
    if let Some(value) = map.get("const") {
        return literal(value);
    }
    if let Some(Value::Array(values)) = map.get("enum") {
        return union(values.iter().map(literal));
    }
    for key in ["anyOf", "oneOf"] {
        if let Some(Value::Array(branches)) = map.get(key) {
            return union(branches.iter().map(|b| ts_type(b, defs, depth)));
        }
    }
    if let Some(Value::Array(branches)) = map.get("allOf") {
        let parts: Vec<String> = branches.iter().map(|b| ts_type(b, defs, depth)).collect();
        return match parts.len() {
            0 => "unknown".to_string(),
            1 => parts.into_iter().next().unwrap_or_default(),
            _ => parts.join(" & "),
        };
    }

    match map.get("type") {
        Some(Value::String(one)) => of_type(one, map, defs, depth),
        Some(Value::Array(many)) => union(
            many.iter()
                .filter_map(Value::as_str)
                .map(|one| of_type(one, map, defs, depth)),
        ),
        _ => "unknown".to_string(),
    }
}

fn of_type(ty: &str, map: &Map<String, Value>, defs: &Defs, depth: usize) -> String {
    match ty {
        "null" => "null".to_string(),
        "boolean" => "boolean".to_string(),
        "integer" | "number" => "number".to_string(),
        "string" => "string".to_string(),
        "array" => array_type(map, defs, depth),
        "object" => object_type(map, defs, depth),
        _ => "unknown".to_string(),
    }
}

fn array_type(map: &Map<String, Value>, defs: &Defs, depth: usize) -> String {
    if let Some(Value::Array(prefix)) = map.get("prefixItems") {
        let parts: Vec<String> = prefix.iter().map(|s| ts_type(s, defs, depth)).collect();
        return format!("[{}]", parts.join(", "));
    }
    match map.get("items") {
        Some(items) => {
            let inner = ts_type(items, defs, depth);
            if inner.contains(' ') || inner.contains('{') {
                format!("Array<{inner}>")
            } else {
                format!("{inner}[]")
            }
        }
        None => "unknown[]".to_string(),
    }
}

fn object_type(map: &Map<String, Value>, defs: &Defs, depth: usize) -> String {
    let properties = map.get("properties").and_then(Value::as_object);
    let required: Vec<&str> = map
        .get("required")
        .and_then(Value::as_array)
        .map(|list| list.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    // An absent `additionalProperties` allows any extra member; `additionalProperties: false`
    // allows none. The two must not be collapsed: an unconstrained `{"type":"object"}` typed as
    // `Record<string, never>` is the empty object, which no real payload satisfies.
    let extra = match map.get("additionalProperties") {
        Some(Value::Bool(false)) => None,
        Some(Value::Bool(true)) => Some("unknown".to_string()),
        Some(schema) => Some(ts_type(schema, defs, depth + 1)),
        None => None,
    };
    let open = !map.contains_key("additionalProperties");
    let Some(properties) = properties else {
        // No declared member, so the object is only its index signature: `Record<string, never>`
        // for the closed `additionalProperties: false`, and `Record<string, unknown>` for an
        // object nothing constrains.
        return match extra {
            Some(value) => format!("Record<string, {value}>"),
            None if open => "Record<string, unknown>".to_string(),
            None => "Record<string, never>".to_string(),
        };
    };
    // `serde_json` keeps object keys sorted, so the member order is stable across runs.
    let mut members: BTreeMap<&String, &Value> = BTreeMap::new();
    for (name, schema) in properties {
        members.insert(name, schema);
    }
    let pad = "  ".repeat(depth + 1);
    let close = "  ".repeat(depth);
    let mut out = String::from("{\n");
    for (name, schema) in members {
        if let Some(doc) = description(schema) {
            out.push_str(&format!("{pad}/** {doc} */\n"));
        }
        let optional = if required.contains(&name.as_str()) {
            ""
        } else {
            "?"
        };
        out.push_str(&format!(
            "{pad}{}{optional}: {};\n",
            member_name(name),
            ts_type(schema, defs, depth + 1)
        ));
    }
    if let Some(value) = extra {
        out.push_str(&format!("{pad}[key: string]: {value};\n"));
    }
    out.push_str(&close);
    out.push('}');
    out
}

/// A property name, quoted when it is not a bare TypeScript identifier.
fn member_name(name: &str) -> String {
    let bare = !name.is_empty()
        && !name.starts_with(|c: char| c.is_ascii_digit())
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if bare {
        name.to_string()
    } else {
        format!("{}", Value::String(name.to_string()))
    }
}

/// A JSON value as a TypeScript literal type.
fn literal(value: &Value) -> String {
    match value {
        Value::Null => "null".to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => format!("{}", Value::String(s.clone())),
        // Arrays and objects have no literal type spelling that stays readable; the schema they
        // come from is still the contract.
        _ => "unknown".to_string(),
    }
}

fn union(parts: impl Iterator<Item = String>) -> String {
    let mut parts: Vec<String> = parts.collect();
    parts.dedup();
    match parts.len() {
        0 => "never".to_string(),
        1 => parts.into_iter().next().unwrap_or_default(),
        _ => parts.join(" | "),
    }
}
