//! Generates the wasm32 command list into `OUT_DIR`: `linkme` does not work on wasm32, so the
//! registry stays empty in the browser until `pemu_wasm::commands` installs this list.
//!
//! It scans `crates/pemu-api/src/commands/*.rs` for a `#[command(` attribute at column 0 followed
//! by a `pub fn <name>(` at column 0, so indented test commands are not taken. `SPEC_<NAME>` is
//! the constant the attribute expands next to the handler.
//! `commands::tests::the_generated_list_is_the_linked_registry` fails if the scan misses one.
//!
//! This script runs on the build host, never in the core, so every cargo path builds the list
//! without a prior generator run.
#![allow(
    clippy::disallowed_methods,
    clippy::disallowed_types,
    reason = "a build script reads sources and writes OUT_DIR on the build host (module doc)"
)]

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets it"));
    let commands = manifest.join("../pemu-api/src/commands");
    println!("cargo::rerun-if-changed={}", commands.display());
    let mut files: Vec<PathBuf> = std::fs::read_dir(&commands)
        .expect("pemu-api's command modules are readable")
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == "rs"))
        .collect();
    files.sort();

    let mut specs: Vec<(String, String)> = Vec::new();
    for file in &files {
        println!("cargo::rerun-if-changed={}", file.display());
        let module = file
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("a UTF-8 module name")
            .to_string();
        if module == "mod" {
            continue;
        }
        let text = std::fs::read_to_string(file).expect("a readable command module");
        let mut in_attribute = false;
        for line in text.lines() {
            if line.starts_with("#[command(") {
                in_attribute = true;
                continue;
            }
            if in_attribute && let Some(rest) = line.strip_prefix("pub fn ") {
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                    .collect();
                specs.push((module.clone(), name));
                in_attribute = false;
            }
        }
    }

    let mut out = String::new();
    out.push_str("// Generated by crates/pemu-wasm/build.rs; never committed.\n");
    let _ = writeln!(
        out,
        "/// Every `#[command]` of `pemu_api::commands`, in module order.\n\
         pub static GENERATED: [pemu_api::spec::CommandSpec; {}] = [",
        specs.len()
    );
    for (module, name) in &specs {
        let _ = writeln!(
            out,
            "    pemu_api::commands::{module}::SPEC_{},",
            name.to_ascii_uppercase()
        );
    }
    out.push_str("];\n");
    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets it")).join("commands.rs");
    std::fs::write(dest, out).expect("OUT_DIR is writable");
}
